/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin source repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomSyntaxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/editorExtension.ts
var import_language3 = require("@codemirror/language");
var import_view2 = require("@codemirror/view");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/cssEditor.ts
var import_autocomplete = require("@codemirror/autocomplete");
var import_commands = require("@codemirror/commands");
var import_language2 = require("@codemirror/language");
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");

// src/cssDeclarations.ts
var import_language = require("@codemirror/language");
var import_highlight = require("@lezer/highlight");
var UNITS = /* @__PURE__ */ new Set([
  "px",
  "em",
  "rem",
  "ex",
  "ch",
  "cap",
  "ic",
  "lh",
  "rlh",
  "vh",
  "vw",
  "vmin",
  "vmax",
  "vi",
  "vb",
  "pt",
  "pc",
  "cm",
  "mm",
  "q",
  "in",
  "fr",
  "deg",
  "rad",
  "grad",
  "turn",
  "s",
  "ms",
  "hz",
  "khz",
  "dpi",
  "dpcm",
  "dppx",
  "x"
]);
var parser = {
  name: "css-declarations",
  startState: () => ({ inValue: false, inComment: false }),
  token(stream, state) {
    if (state.inComment) {
      if (stream.match(/.*?\*\//)) {
        state.inComment = false;
      } else {
        stream.skipToEnd();
      }
      return "comment";
    }
    if (stream.sol() && !stream.match(/^[ \t]/)) {
      state.inValue = false;
    }
    if (stream.eatSpace()) {
      return null;
    }
    if (stream.match(/\/\*/)) {
      if (!stream.match(/.*?\*\//)) {
        state.inComment = true;
        stream.skipToEnd();
      }
      return "comment";
    }
    if (stream.peek() === '"' || stream.peek() === "'") {
      return readString(stream);
    }
    if (state.inValue) {
      if (stream.match(/^;/)) {
        state.inValue = false;
        return "punct";
      }
      if (stream.match(/^!important/i)) {
        return "important";
      }
      if (stream.match(/^#[0-9a-fA-F]{3,8}\b/)) {
        return "number";
      }
      if (stream.match(/^--[A-Za-z0-9_-]+/)) {
        return "variable";
      }
      if (stream.match(/^-?(?:\d+\.?\d*|\.\d+)/)) {
        return "number";
      }
      if (stream.match(/^[A-Za-z][A-Za-z0-9_-]*(?=\s*\()/)) {
        return "fn";
      }
      if (stream.match(/^[A-Za-z-][A-Za-z0-9_-]*/)) {
        return UNITS.has(stream.current().toLowerCase()) ? "unit" : "value";
      }
      if (stream.match(/^%/)) {
        return "unit";
      }
      stream.next();
      return "punct";
    }
    if (stream.match(/^[:;{}]/)) {
      state.inValue = stream.current() === ":";
      return "punct";
    }
    if (stream.match(/^--[A-Za-z0-9_-]+/)) {
      return "prop";
    }
    if (stream.match(/^[A-Za-z*-][A-Za-z0-9_-]*/)) {
      return "prop";
    }
    stream.next();
    return "punct";
  },
  languageData: {
    commentTokens: { block: { open: "/*", close: "*/" } },
    closeBrackets: { brackets: ["(", "'", '"'] },
    autocomplete: cssDeclarationsCompletion
  },
  tokenTable: {
    comment: import_highlight.tags.comment,
    prop: import_highlight.tags.propertyName,
    variable: import_highlight.tags.variableName,
    fn: import_highlight.tags.function(import_highlight.tags.variableName),
    number: import_highlight.tags.number,
    unit: import_highlight.tags.unit,
    value: import_highlight.tags.atom,
    string: import_highlight.tags.string,
    important: import_highlight.tags.keyword,
    punct: import_highlight.tags.punctuation
  }
};
function readString(stream) {
  const quote = stream.next();
  while (!stream.eol()) {
    const ch = stream.next();
    if (ch === "\\") {
      stream.next();
      continue;
    }
    if (ch === quote) {
      break;
    }
  }
  return "string";
}
var cssDeclarations = import_language.StreamLanguage.define(parser);
var PROPERTIES = [
  "align-content",
  "align-items",
  "align-self",
  "all",
  "animation",
  "animation-delay",
  "animation-duration",
  "animation-iteration-count",
  "animation-name",
  "animation-timing-function",
  "aspect-ratio",
  "backdrop-filter",
  "background",
  "background-attachment",
  "background-blend-mode",
  "background-clip",
  "background-color",
  "background-image",
  "background-position",
  "background-repeat",
  "background-size",
  "block-size",
  "border",
  "border-block",
  "border-bottom",
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-collapse",
  "border-color",
  "border-inline",
  "border-left",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-spacing",
  "border-style",
  "border-top",
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width",
  "bottom",
  "box-shadow",
  "box-sizing",
  "caption-side",
  "caret-color",
  "clear",
  "clip-path",
  "color",
  "color-scheme",
  "column-gap",
  "column-rule",
  "column-span",
  "columns",
  "content",
  "counter-increment",
  "cursor",
  "direction",
  "display",
  "empty-cells",
  "filter",
  "flex",
  "flex-basis",
  "flex-direction",
  "flex-flow",
  "flex-grow",
  "flex-shrink",
  "flex-wrap",
  "float",
  "font",
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-size",
  "font-size-adjust",
  "font-stretch",
  "font-style",
  "font-variant",
  "font-variant-numeric",
  "font-weight",
  "gap",
  "grid",
  "grid-area",
  "grid-auto-columns",
  "grid-auto-flow",
  "grid-auto-rows",
  "grid-column",
  "grid-column-end",
  "grid-column-start",
  "grid-gap",
  "grid-row",
  "grid-row-end",
  "grid-row-start",
  "grid-template",
  "grid-template-areas",
  "grid-template-columns",
  "grid-template-rows",
  "height",
  "hyphens",
  "inline-size",
  "inset",
  "isolation",
  "justify-content",
  "justify-items",
  "justify-self",
  "left",
  "letter-spacing",
  "line-break",
  "line-height",
  "list-style",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "margin",
  "margin-block",
  "margin-block-end",
  "margin-block-start",
  "margin-bottom",
  "margin-inline",
  "margin-inline-end",
  "margin-inline-start",
  "margin-left",
  "margin-right",
  "margin-top",
  "mask",
  "max-block-size",
  "max-height",
  "max-inline-size",
  "max-width",
  "min-block-size",
  "min-height",
  "min-inline-size",
  "min-width",
  "mix-blend-mode",
  "object-fit",
  "object-position",
  "opacity",
  "order",
  "outline",
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
  "overflow",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "overscroll-behavior",
  "padding",
  "padding-block",
  "padding-block-end",
  "padding-block-start",
  "padding-bottom",
  "padding-inline",
  "padding-inline-end",
  "padding-inline-start",
  "padding-left",
  "padding-right",
  "padding-top",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "perspective",
  "place-content",
  "place-items",
  "place-self",
  "pointer-events",
  "position",
  "quotes",
  "resize",
  "right",
  "rotate",
  "row-gap",
  "scale",
  "scroll-behavior",
  "scroll-margin",
  "scroll-padding",
  "tab-size",
  "table-layout",
  "text-align",
  "text-align-last",
  "text-decoration",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-style",
  "text-decoration-thickness",
  "text-emphasis",
  "text-indent",
  "text-justify",
  "text-overflow",
  "text-rendering",
  "text-shadow",
  "text-transform",
  "text-underline-offset",
  "top",
  "touch-action",
  "transform",
  "transform-origin",
  "transition",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "translate",
  "unicode-bidi",
  "user-select",
  "vertical-align",
  "visibility",
  "white-space",
  "widows",
  "width",
  "will-change",
  "word-break",
  "word-spacing",
  "word-wrap",
  "writing-mode",
  "z-index",
  "zoom"
];
var VALUE_KEYWORDS = [
  "auto",
  "none",
  "normal",
  "inherit",
  "initial",
  "unset",
  "revert",
  "bold",
  "bolder",
  "lighter",
  "italic",
  "oblique",
  "underline",
  "overline",
  "line-through",
  "solid",
  "dashed",
  "dotted",
  "double",
  "groove",
  "ridge",
  "inset",
  "outset",
  "hidden",
  "visible",
  "block",
  "inline",
  "inline-block",
  "inline-flex",
  "inline-grid",
  "flex",
  "grid",
  "contents",
  "table",
  "absolute",
  "relative",
  "fixed",
  "sticky",
  "static",
  "left",
  "right",
  "center",
  "justify",
  "top",
  "bottom",
  "start",
  "end",
  "nowrap",
  "pre",
  "pre-wrap",
  "ellipsis",
  "uppercase",
  "lowercase",
  "capitalize",
  "small-caps",
  "pointer",
  "default",
  "ease",
  "ease-in",
  "ease-out",
  "ease-in-out",
  "linear",
  "cover",
  "contain",
  "repeat",
  "no-repeat"
];
var COLOR_KEYWORDS = [
  "transparent",
  "currentColor",
  "red",
  "orange",
  "yellow",
  "green",
  "cyan",
  "blue",
  "purple",
  "pink",
  "white",
  "black",
  "gray",
  "grey",
  "silver",
  "gold"
];
var OBSIDIAN_VARIABLES = [
  "--text-normal",
  "--text-muted",
  "--text-faint",
  "--text-accent",
  "--text-accent-hover",
  "--text-error",
  "--text-warning",
  "--text-success",
  "--text-highlight-bg",
  "--text-selection",
  "--background-primary",
  "--background-primary-alt",
  "--background-secondary",
  "--background-secondary-alt",
  "--background-modifier-border",
  "--background-modifier-hover",
  "--background-modifier-active-hover",
  "--background-modifier-form-field",
  "--interactive-normal",
  "--interactive-hover",
  "--interactive-accent",
  "--interactive-accent-hover",
  "--color-red",
  "--color-orange",
  "--color-yellow",
  "--color-green",
  "--color-cyan",
  "--color-blue",
  "--color-purple",
  "--color-pink",
  "--font-ui-smaller",
  "--font-ui-small",
  "--font-ui-medium",
  "--font-ui-large",
  "--font-monospace",
  "--radius-s",
  "--radius-m",
  "--radius-l",
  "--size-4-1",
  "--size-4-2",
  "--size-4-3",
  "--size-4-4",
  "--size-4-6",
  "--size-4-8"
];
var COLOR_PROPERTIES = /* @__PURE__ */ new Set([
  "color",
  "background",
  "background-color",
  "border-color",
  "border-top-color",
  "border-right-color",
  "border-bottom-color",
  "border-left-color",
  "caret-color",
  "outline-color",
  "text-decoration-color",
  "text-emphasis-color",
  "column-rule-color",
  "fill",
  "stroke"
]);
function toOptions(values, type) {
  return values.map((label) => ({ label, type }));
}
var PROPERTY_OPTIONS = toOptions(PROPERTIES, "property");
var KEYWORD_OPTIONS = toOptions(VALUE_KEYWORDS, "keyword");
var COLOR_OPTIONS = toOptions(COLOR_KEYWORDS, "constant");
var VARIABLE_OPTIONS = OBSIDIAN_VARIABLES.map((label) => ({
  label,
  type: "variable",
  detail: "Obsidian"
}));
function currentProperty(before) {
  const match = before.match(/([A-Za-z-][A-Za-z0-9_-]*)\s*:[^:;]*$/);
  return match ? match[1].toLowerCase() : "";
}
function cssDeclarationsCompletion(context) {
  const line = context.state.doc.lineAt(context.pos);
  const before = line.text.slice(0, context.pos - line.from);
  const colon = before.lastIndexOf(":");
  const semicolon = before.lastIndexOf(";");
  if (colon > semicolon) {
    const word2 = context.matchBefore(/[\w-]*/);
    if (!word2 && !context.explicit) {
      return null;
    }
    const prop = currentProperty(before);
    const options = COLOR_PROPERTIES.has(prop) ? [...COLOR_OPTIONS, ...VARIABLE_OPTIONS, ...KEYWORD_OPTIONS] : [...KEYWORD_OPTIONS, ...VARIABLE_OPTIONS, ...COLOR_OPTIONS];
    return {
      from: word2 ? word2.from : context.pos,
      options,
      validFor: /^[\w-]*$/
    };
  }
  const word = context.matchBefore(/[-*\w]*/);
  if (!word && !context.explicit) {
    return null;
  }
  return {
    from: word ? word.from : context.pos,
    options: PROPERTY_OPTIONS,
    validFor: /^[-*\w]*$/
  };
}

// src/cssEditor.ts
var TOKEN_CLASS = {
  comment: "cs-tok-comment",
  prop: "cs-tok-prop",
  propertyName: "cs-tok-prop",
  variable: "cs-tok-var",
  variableName: "cs-tok-var",
  fn: "cs-tok-fn",
  number: "cs-tok-num",
  unit: "cs-tok-unit",
  value: "cs-tok-val",
  atom: "cs-tok-val",
  string: "cs-tok-str",
  important: "cs-tok-kw",
  keyword: "cs-tok-kw",
  punct: "cs-tok-punct",
  punctuation: "cs-tok-punct"
};
function buildHighlight(view) {
  const builder = [];
  for (const { from, to } of view.visibleRanges) {
    (0, import_language2.syntaxTree)(view.state).iterate({
      from,
      to,
      enter: (node) => {
        const cls = TOKEN_CLASS[node.name];
        if (cls && node.from < node.to) {
          builder.push(
            import_view.Decoration.mark({ class: cls }).range(node.from, node.to)
          );
        }
      }
    });
  }
  return import_view.Decoration.set(builder, true);
}
var cssHighlightPlugin = import_view.ViewPlugin.fromClass(
  class {
    constructor(view) {
      this.decorations = buildHighlight(view);
    }
    update(update) {
      if (update.docChanged || update.viewportChanged) {
        this.decorations = buildHighlight(update.view);
      }
    }
  },
  { decorations: (v) => v.decorations }
);
function createCssEditor(parent, doc, options = {}) {
  const extensions = [
    import_view.EditorView.editorAttributes.of({ class: "custom-syntax-cm-editor" }),
    (0, import_view.lineNumbers)(),
    (0, import_view.highlightActiveLineGutter)(),
    (0, import_view.highlightActiveLine)(),
    (0, import_commands.history)(),
    (0, import_view.drawSelection)(),
    (0, import_view.rectangularSelection)(),
    (0, import_language2.bracketMatching)(),
    (0, import_autocomplete.closeBrackets)(),
    (0, import_autocomplete.autocompletion)({ icons: false }),
    // Keep completion/lint popups inside our own container so they pick up
    // scoped styles instead of leaking into Obsidian's global editors.
    (0, import_view.tooltips)({ parent }),
    import_view.EditorView.lineWrapping,
    import_language2.indentUnit.of("  "),
    cssDeclarations,
    cssHighlightPlugin,
    // Ctrl/Cmd+Enter submits the surrounding dialog before the default
    // keymap can turn it into a newline.
    import_state.Prec.highest(
      import_view.keymap.of([
        {
          key: "Mod-Enter",
          run: () => {
            if (options.onSubmit) {
              options.onSubmit();
              return true;
            }
            return false;
          }
        }
      ])
    ),
    import_view.keymap.of([
      ...import_autocomplete.closeBracketsKeymap,
      ...import_commands.defaultKeymap,
      ...import_commands.historyKeymap,
      ...import_autocomplete.completionKeymap,
      import_commands.indentWithTab
    ])
  ];
  if (options.placeholderText) {
    extensions.push((0, import_view.placeholder)(options.placeholderText));
  }
  if (options.onChange) {
    const notify = options.onChange;
    extensions.push(
      import_view.EditorView.updateListener.of((update) => {
        if (update.docChanged) {
          notify(update.state.doc.toString());
        }
      })
    );
  }
  if (options.ariaLabel) {
    extensions.push(
      import_view.EditorView.contentAttributes.of({
        "aria-label": options.ariaLabel,
        autocapitalize: "off",
        autocorrect: "off",
        spellcheck: "false"
      })
    );
  }
  const view = new import_view.EditorView({
    state: import_state.EditorState.create({ doc, extensions }),
    parent
  });
  return {
    getValue() {
      return view.state.doc.toString();
    },
    setValue(value) {
      view.dispatch({
        changes: { from: 0, to: view.state.doc.length, insert: value }
      });
    },
    focus() {
      view.focus();
    },
    destroy() {
      view.destroy();
    }
  };
}

// src/settings.ts
var DEFAULT_SETTINGS = {
  language: "system",
  rules: [
    {
      id: "rounded-box",
      name: "\u5706\u89D2\u8FB9\u6846",
      enabled: true,
      kind: "inline",
      open: "++",
      close: "++",
      readType: false,
      captureParams: false,
      css: `border: 1px solid var(--interactive-accent);
border-radius: 6px;
padding: 1px 5px;`,
      className: ""
    },
    {
      id: "fenced-note",
      name: "\u56F4\u680F\u5757 (:::note)",
      enabled: true,
      kind: "fenced",
      open: ":::",
      close: ":::",
      readType: true,
      captureParams: false,
      css: "",
      className: ""
    },
    {
      id: "multiline-plus",
      name: "\u591A\u884C\u5757 (++)",
      enabled: true,
      kind: "multiline",
      open: "++",
      close: "++",
      readType: false,
      captureParams: false,
      css: "",
      className: ""
    }
  ],
  showRibbon: true
};
function newRuleId() {
  return `r${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}
function normalizeRule(r) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  const kind = r.kind === "fenced" || r.kind === "multiline" || r.kind === "callout" ? r.kind : "inline";
  const legacy = r;
  const open = (_b = (_a = r.open) != null ? _a : legacy.delimiter) != null ? _b : "";
  const close = (_c = r.close) != null ? _c : kind === "inline" ? open : kind === "fenced" ? open : "";
  return {
    id: typeof r.id === "string" && r.id ? r.id : newRuleId(),
    name: typeof r.name === "string" ? r.name : "",
    enabled: (_d = r.enabled) != null ? _d : true,
    kind,
    open,
    close,
    readType: (_e = r.readType) != null ? _e : kind === "callout" ? true : kind === "fenced",
    captureParams: (_f = r.captureParams) != null ? _f : false,
    css: (_g = r.css) != null ? _g : "",
    className: sanitizeClassName((_h = r.className) != null ? _h : ""),
    conflictWithId: (_i = r.conflictWithId) != null ? _i : null
  };
}
function ruleClassName(id) {
  return `custom-syntax-${id}`;
}
function sanitizeClassName(raw) {
  return (raw != null ? raw : "").split(/\s+/).map((token) => token.trim()).filter((token) => /^-?[A-Za-z_][A-Za-z0-9_-]*$/.test(token)).join(" ");
}
function ruleContentClass(id) {
  return `${ruleClassName(id)}-content`;
}
function contentClasses(rule) {
  const parts = ["custom-syntax-content", ruleContentClass(rule.id)];
  const extra = sanitizeClassName(rule.className);
  if (extra) {
    parts.push(extra);
  }
  return parts.join(" ");
}
function exportRulesAsCss(rules) {
  var _a;
  const blocks = [];
  for (const rule of rules) {
    const css = ((_a = rule.css) != null ? _a : "").trim();
    if (!css) {
      continue;
    }
    const extra = sanitizeClassName(rule.className);
    const selector = extra ? `.${extra.split(" ").join(".")}` : rule.kind === "inline" ? `.${ruleContentClass(rule.id)}` : `.cs-block-${rule.id}`;
    const label = rule.name || rule.open || rule.id;
    const declarations = css.split(";").map((decl) => decl.trim()).filter(Boolean).map((decl) => `	${decl};`).join("\n");
    blocks.push(
      `/* ${label} \u2014 ${rule.open} */
${selector} {
${declarations}
}`
    );
  }
  if (blocks.length === 0) {
    return "";
  }
  return [
    "/* Generated by the Custom Syntax plugin. */",
    "/* Paste into a CSS snippet, then clear the rule's declarations so the snippet takes over. */",
    "",
    ...blocks
  ].join("\n");
}
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function delimitersConflict(a, b) {
  if (!a || !b) {
    return false;
  }
  return a === b || a.includes(b) || b.includes(a);
}
var BUILTIN = [
  { delim: "**", zh: "\u7C97\u4F53", en: "Bold" },
  { delim: "__", zh: "\u7C97\u4F53", en: "Bold" },
  { delim: "*", zh: "\u659C\u4F53", en: "Italic" },
  { delim: "_", zh: "\u659C\u4F53", en: "Italic" },
  { delim: "~~", zh: "\u5220\u9664\u7EBF", en: "Strikethrough" },
  { delim: "==", zh: "\u9AD8\u4EAE", en: "Highlight" },
  { delim: "`", zh: "\u884C\u5185\u4EE3\u7801", en: "Inline code" },
  { delim: "```", zh: "\u4EE3\u7801\u5757", en: "Code block" },
  { delim: "%%", zh: "\u6CE8\u91CA", en: "Comment" },
  { delim: "$", zh: "\u6570\u5B66\u516C\u5F0F", en: "Math" },
  { delim: "#", zh: "\u6807\u9898", en: "Heading" },
  { delim: ">", zh: "\u5F15\u7528", en: "Blockquote" },
  { delim: "|", zh: "\u8868\u683C", en: "Table" },
  { delim: "[[", zh: "\u5185\u90E8\u94FE\u63A5", en: "Wikilink" },
  { delim: "![[", zh: "\u5D4C\u5165", en: "Embed" },
  { delim: "[", zh: "\u94FE\u63A5", en: "Link" },
  { delim: "]", zh: "\u94FE\u63A5", en: "Link" },
  { delim: "(", zh: "\u94FE\u63A5", en: "Link" },
  { delim: ")", zh: "\u94FE\u63A5", en: "Link" },
  { delim: "!", zh: "\u56FE\u7247", en: "Image" },
  { delim: "^", zh: "\u4E0A\u6807/\u811A\u6CE8", en: "Superscript/Footnote" },
  { delim: "~", zh: "\u4E0B\u6807", en: "Subscript" }
];
function findBuiltinConflict(delim) {
  for (const b of BUILTIN) {
    if (delimitersConflict(delim, b.delim)) {
      return b;
    }
  }
  return null;
}
function findCustomConflict(delim, rules, excludeId) {
  for (const r of rules) {
    if (excludeId && r.id === excludeId) {
      continue;
    }
    if (delimitersConflict(delim, r.open)) {
      return r;
    }
  }
  return null;
}
var STRINGS = {
  zh: {
    pluginName: "\u81EA\u5B9A\u4E49\u8BED\u6CD5",
    language: "\u8BED\u8A00",
    addRule: "\u6DFB\u52A0\u89C4\u5219",
    followSystem: "\u8DDF\u968F\u7CFB\u7EDF",
    toggle: "\u542F\u7528\u6216\u7981\u7528",
    edit: "\u7F16\u8F91",
    delete: "\u5220\u9664",
    deleteConfirm: "\u786E\u5B9A\u8981\u5220\u9664\u89C4\u5219\u300C{name}\u300D\u5417\uFF1F",
    createTitle: "\u65B0\u5EFA\u89C4\u5219",
    editTitle: "\u7F16\u8F91\u89C4\u5219",
    ruleName: "\u89C4\u5219\u540D",
    ruleNamePlaceholder: "\u7ED9\u89C4\u5219\u8D77\u4E2A\u540D\u5B57",
    delimiter: "\u5206\u9694\u7B26",
    delimiterDesc: "\u5305\u88F9\u6587\u5B57\u7684\u6807\u8BB0\uFF0C\u4F8B\u5982 ++",
    css: "\u6837\u5F0F\u58F0\u660E",
    cssDesc: "\u53EA\u5199 CSS \u82B1\u62EC\u53F7 { } \u91CC\u7684\u5185\u5BB9\uFF0C\u4F8B\u5982 color: red;\u3002\u7559\u7A7A\u5219\u5B8C\u5168\u7531\u4E0B\u65B9\u7C7B\u540D\u5728\u4F60\u81EA\u5DF1\u7684 CSS \u7247\u6BB5\u4E2D\u51B3\u5B9A\u6837\u5F0F\u3002",
    cssPlaceholder: `border: 1px solid var(--interactive-accent);
border-radius: 6px;
padding: 1px 5px;`,
    cssAria: "CSS \u6837\u5F0F\u58F0\u660E",
    visualEdit: "\u53EF\u89C6\u5316\u7F16\u8F91",
    visualEditHint: "\u5373\u5C06\u63A8\u51FA\uFF1A\u7528\u56FE\u5F62\u754C\u9762\u8C03\u6574\u6837\u5F0F\uFF0C\u65E0\u9700\u624B\u5199 CSS",
    className: "\u7C7B\u540D\uFF08\u53EF\u9009\uFF09",
    classNameDesc: "\u9644\u52A0\u5230\u5339\u914D\u6587\u5B57\u4E0A\u7684 CSS \u7C7B\u540D\uFF0C\u591A\u4E2A\u7528\u7A7A\u683C\u5206\u9694\u3002\u6837\u5F0F\u58F0\u660E\u7559\u7A7A\u65F6\uFF0C\u6837\u5F0F\u5B8C\u5168\u7531\u4F60\u5728 CSS \u7247\u6BB5\u4E2D\u4E3A\u8FD9\u4E2A\u7C7B\u5199\u7684\u89C4\u5219\u51B3\u5B9A\u3002",
    classNamePlaceholder: "my-highlight",
    exportName: "\u5BFC\u51FA\u4E3A CSS \u7247\u6BB5",
    exportDesc: "\u628A\u89C4\u5219\u7684\u6837\u5F0F\u58F0\u660E\u5BFC\u51FA\u6210 CSS \u7247\u6BB5\u3002\u7C98\u5230\u4F60\u7684 CSS \u7247\u6BB5\u6587\u4EF6\u5E76\u542F\u7528\u540E\uFF0C\u6E05\u7A7A\u89C4\u5219\u7684\u6837\u5F0F\u58F0\u660E\u5373\u53EF\u6539\u7531\u7247\u6BB5\u63A7\u5236\uFF0C\u6837\u5F0F\u4E5F\u5C31\u80FD\u88AB\u4E3B\u9898\u590D\u7528\u548C\u8986\u76D6\u3002",
    exportBtn: "\u5BFC\u51FA",
    exportTitle: "\u5BFC\u51FA CSS \u7247\u6BB5",
    exportEmpty: "\u8FD8\u6CA1\u6709\u89C4\u5219\u586B\u5199\u6837\u5F0F\u58F0\u660E\uFF0C\u6CA1\u6709\u53EF\u5BFC\u51FA\u7684\u5185\u5BB9\u3002",
    copy: "\u590D\u5236\u5230\u526A\u8D34\u677F",
    copied: "\u5DF2\u590D\u5236",
    copyFailed: "\u590D\u5236\u5931\u8D25\uFF0C\u8BF7\u624B\u52A8\u9009\u4E2D\u590D\u5236",
    cancel: "\u53D6\u6D88",
    create: "\u521B\u5EFA",
    save: "\u4FDD\u5B58",
    delimiterRequired: "\u6807\u8BB0\u4E0D\u80FD\u4E3A\u7A7A",
    conflictBuiltin: "\u4E0E Markdown \u5185\u7F6E\u8BED\u6CD5\u300C{name}\u300D\u51B2\u7A81",
    conflictCustomCreate: "\u4E0E\u81EA\u5B9A\u4E49\u8BED\u6CD5\u300C{name}\u300D\u51B2\u7A81\uFF0C\u518D\u6B21\u786E\u8BA4\u5C06\u521B\u5EFA\u5E76\u7981\u7528",
    conflictCustomSave: "\u4E0E\u81EA\u5B9A\u4E49\u8BED\u6CD5\u300C{name}\u300D\u51B2\u7A81\uFF0C\u518D\u6B21\u786E\u8BA4\u5C06\u4FDD\u5B58\u5E76\u7981\u7528",
    conflictAnnotation: "\u4E0E\u300C{name}\u300D\u51B2\u7A81",
    untitled: "\u672A\u547D\u540D",
    back: "\u8FD4\u56DE",
    noRules: "\u8FD8\u6CA1\u6709\u89C4\u5219\uFF0C\u70B9\u51FB\u53F3\u4E0A\u89D2\u300C\u6DFB\u52A0\u89C4\u5219\u300D\u65B0\u5EFA\u4E00\u6761\u3002",
    other: "\u5176\u4ED6",
    exportGroup: "\u5BFC\u51FA",
    toolbarIcon: "\u5DE5\u5177\u680F\u56FE\u6807",
    toolbarIconDesc: "\u5728\u5DE6\u4FA7\u529F\u80FD\u680F\u663E\u793A\u4E00\u4E2A\u56FE\u6807\uFF0C\u70B9\u51FB\u5373\u53EF\u6253\u5F00\u89C4\u5219\u7BA1\u7406\u5668\u9762\u677F\u3002",
    invokePanel: "\u5524\u8D77\u9762\u677F",
    invokePanelDesc: "\u5728\u53F3\u4FA7\u8FB9\u680F\u6253\u5F00\u89C4\u5219\u7BA1\u7406\u5668\u3002",
    openPanel: "\u6253\u5F00\u9762\u677F",
    docs: "\u8BF4\u660E\u6587\u6863",
    docsTitle: "\u81EA\u5B9A\u4E49\u8BED\u6CD5 - \u8BF4\u660E",
    docsRepo: "\u5728 GitHub \u4E0A\u67E5\u770B",
    docsOpen: "\u6253\u5F00",
    close: "\u5173\u95ED",
    languageSwitch: "\u5207\u6362\u8BED\u8A00",
    openSettings: "\u8BBE\u7F6E",
    category: "\u8BED\u6CD5\u7C7B\u522B",
    enabledLabel: "\u542F\u7528",
    catInline: "\u884C\u5185\u914D\u5BF9",
    catFenced: "\u56F4\u680F\u5757",
    catMultiline: "\u591A\u884C\u5757",
    catCallout: "\u81EA\u5B9A\u4E49 Callout",
    openMarker: "\u8D77\u59CB\u6807\u8BB0",
    openMarkerDesc: "\u5757\u8D77\u59CB\u884C\u7684\u6807\u8BB0\uFF0C\u4F8B\u5982 ::: \u6216 ++",
    closeMarker: "\u7ED3\u675F\u6807\u8BB0",
    closeMarkerDesc: "\u5757\u7ED3\u675F\u884C\u7684\u6807\u8BB0\uFF0C\u4F8B\u5982 ::: \u6216 ++",
    typeName: "\u7C7B\u578B\u540D",
    typeNameDesc: "Obsidian callout \u7C7B\u578B\u540D\uFF0C\u4F8B\u5982 mynote\uFF1B\u5728\u7B14\u8BB0\u91CC\u7528 > [!mynote] \u89E6\u53D1",
    readType: "\u8BFB\u53D6\u7C7B\u578B",
    readTypeDesc: "\u4ECE\u8D77\u59CB\u884C\u8BFB\u53D6\u7C7B\u578B\uFF08\u5982 :::note \u7684\u7C7B\u578B\u4E3A note\uFF09\uFF0C\u4F5C\u4E3A\u7C7B\u540D\u94A9\u5B50",
    captureParams: "\u6355\u83B7\u53C2\u6570",
    captureParamsDesc: "\u5728\u6807\u8BB0\u540E\u89E3\u6790 { .class #id k=v } \u5E76\u52A8\u6001\u5957\u7528",
    markerPlaceholder: ":::",
    typePlaceholder: "mynote"
  },
  en: {
    pluginName: "Custom Syntax",
    language: "Language",
    addRule: "Add rule",
    followSystem: "Follow system",
    toggle: "Enable or disable",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: 'Delete rule "{name}"?',
    createTitle: "New rule",
    editTitle: "Edit rule",
    ruleName: "Rule name",
    ruleNamePlaceholder: "Name this rule",
    delimiter: "Delimiter",
    delimiterDesc: "The marker that wraps the text, e.g. ++",
    css: "Style declarations",
    cssDesc: "Write only what goes inside the CSS curly braces { }, e.g. color: red;. Leave empty and the class below decides the styling from your own CSS snippet.",
    cssPlaceholder: `border: 1px solid var(--interactive-accent);
border-radius: 6px;
padding: 1px 5px;`,
    cssAria: "CSS style declarations",
    visualEdit: "Visual editor",
    visualEditHint: "Coming soon: tweak styles in a GUI instead of writing CSS by hand",
    className: "Class name (optional)",
    classNameDesc: "CSS class names added to the matched text, separated by spaces. With the declarations left empty, styling comes entirely from the rule you write for this class in a CSS snippet.",
    classNamePlaceholder: "my-highlight",
    exportName: "Export as CSS snippet",
    exportDesc: "Export rule declarations as a CSS snippet. Paste it into a CSS snippet file and enable it, then clear the rule's declarations so the snippet takes over \u2014 that way styles can be reused and overridden by themes.",
    exportBtn: "Export",
    exportTitle: "Export CSS snippet",
    exportEmpty: "No rule has declarations yet, so there is nothing to export.",
    copy: "Copy to clipboard",
    copied: "Copied",
    copyFailed: "Copy failed \u2014 select and copy manually",
    cancel: "Cancel",
    create: "Create",
    save: "Save",
    delimiterRequired: "Marker is required",
    conflictBuiltin: 'Conflicts with built-in Markdown syntax "{name}"',
    conflictCustomCreate: 'Conflicts with custom syntax "{name}" \u2014 confirm again to create (disabled)',
    conflictCustomSave: 'Conflicts with custom syntax "{name}" \u2014 confirm again to save (disabled)',
    conflictAnnotation: 'Conflicts with "{name}"',
    untitled: "Untitled",
    back: "Back",
    noRules: 'No rules yet \u2014 click "Add rule" in the top right to create one.',
    other: "Other",
    exportGroup: "Export",
    toolbarIcon: "Toolbar icon",
    toolbarIconDesc: "Show an icon in the left ribbon that opens the rule manager panel.",
    invokePanel: "Open panel",
    invokePanelDesc: "Open the rule manager in the right sidebar.",
    openPanel: "Open panel",
    docs: "Documentation",
    docsTitle: "Custom Syntax - Guide",
    docsRepo: "View on GitHub",
    docsOpen: "Open",
    close: "Close",
    languageSwitch: "Switch language",
    openSettings: "Settings",
    category: "Syntax category",
    enabledLabel: "Enabled",
    catInline: "Inline pair",
    catFenced: "Fenced block",
    catMultiline: "Multiline block",
    catCallout: "Custom callout",
    openMarker: "Opening marker",
    openMarkerDesc: "The marker on the block's opening line, e.g. ::: or ++",
    closeMarker: "Closing marker",
    closeMarkerDesc: "The marker on the block's closing line, e.g. ::: or ++",
    typeName: "Type name",
    typeNameDesc: "The Obsidian callout type name, e.g. mynote; trigger with > [!mynote]",
    readType: "Read type",
    readTypeDesc: "Read the type from the opening line (e.g. :::note -> note) as a class hook",
    captureParams: "Capture parameters",
    captureParamsDesc: "Parse { .class #id k=v } after the match and apply it dynamically",
    markerPlaceholder: ":::",
    typePlaceholder: "mynote"
  }
};
function resolveLanguage(lang) {
  if (lang === "system") {
    const nav = typeof navigator !== "undefined" ? navigator.language || "" : "";
    return nav.toLowerCase().startsWith("zh") ? "zh" : "en";
  }
  return lang;
}
function getStrings(lang) {
  var _a;
  return (_a = STRINGS[lang]) != null ? _a : STRINGS.zh;
}
function stringsFor(lang) {
  return getStrings(resolveLanguage(lang));
}
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message, confirmLabel, cancelLabel, onConfirm) {
    super(app);
    this.message = message;
    this.confirmLabel = confirmLabel;
    this.cancelLabel = cancelLabel;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", {
      cls: "custom-syntax-confirm-message",
      text: this.message
    });
    const btnRow = contentEl.createDiv({ cls: "custom-syntax-modal-actions" });
    const cancelBtn = btnRow.createEl("button", { text: this.cancelLabel });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = btnRow.createEl("button", {
      text: this.confirmLabel,
      cls: "mod-warning"
    });
    confirmBtn.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
  }
};
var RuleForm = class {
  constructor(container, plugin, rule, onSubmit) {
    this.kind = "inline";
    this.pendingCustomConflict = null;
    this.enabled = true;
    this.readType = false;
    this.captureParams = false;
    this.plugin = plugin;
    this.rule = rule;
    this.onSubmit = onSubmit;
    this.build(container);
  }
  build(container) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _i, _j;
    const t = stringsFor(this.plugin.settings.language);
    this.kind = (_b = (_a = this.rule) == null ? void 0 : _a.kind) != null ? _b : "inline";
    this.enabled = (_d = (_c = this.rule) == null ? void 0 : _c.enabled) != null ? _d : true;
    this.readType = (_f = (_e = this.rule) == null ? void 0 : _e.readType) != null ? _f : this.kind === "fenced" || this.kind === "callout";
    this.captureParams = (_h = (_g = this.rule) == null ? void 0 : _g.captureParams) != null ? _h : false;
    const cat = new import_obsidian.Setting(container).setName(t.category);
    const seg = cat.controlEl.createDiv({ cls: "custom-syntax-cat-seg" });
    const kinds = ["inline", "fenced", "multiline", "callout"];
    const labelOf = {
      inline: t.catInline,
      fenced: t.catFenced,
      multiline: t.catMultiline,
      callout: t.catCallout
    };
    const buttons = {};
    for (const k of kinds) {
      const b = seg.createEl("button", {
        text: labelOf[k],
        cls: "custom-syntax-cat-btn"
      });
      if (k === this.kind) b.addClass("is-active");
      b.addEventListener("click", () => {
        if (this.kind === k) return;
        this.kind = k;
        for (const kk of kinds) {
          buttons[kk].toggleClass("is-active", kk === k);
        }
        this.renderConditional();
      });
      buttons[k] = b;
    }
    new import_obsidian.Setting(container).setName(t.ruleName).addText((text) => {
      var _a2, _b2;
      this.nameInput = text.inputEl;
      text.setValue((_b2 = (_a2 = this.rule) == null ? void 0 : _a2.name) != null ? _b2 : "").setPlaceholder(t.ruleNamePlaceholder);
    });
    new import_obsidian.Setting(container).setName(t.enabledLabel).addToggle((tg) => {
      tg.setValue(this.enabled);
      tg.onChange((v) => {
        this.enabled = v;
      });
    });
    this.conditionalEl = container.createDiv({
      cls: "custom-syntax-conditional"
    });
    this.renderConditional();
    new import_obsidian.Setting(container).setName(t.className).addText((text) => {
      var _a2, _b2;
      this.classInput = text.inputEl;
      text.setValue((_b2 = (_a2 = this.rule) == null ? void 0 : _a2.className) != null ? _b2 : "").setPlaceholder(t.classNamePlaceholder);
    });
    const cssSetting = new import_obsidian.Setting(container).setName(t.css);
    cssSetting.settingEl.addClass("custom-syntax-stacked");
    const cssRow = cssSetting.controlEl.createDiv({
      cls: "custom-syntax-css-row"
    });
    const cssHost = cssRow.createDiv({
      cls: "custom-syntax-css-editor"
    });
    this.cssEditor = createCssEditor(
      cssHost,
      (_j = (_i = this.rule) == null ? void 0 : _i.css) != null ? _j : DEFAULT_SETTINGS.rules[0].css,
      {
        placeholderText: t.cssPlaceholder,
        ariaLabel: t.cssAria,
        onSubmit: () => this.onSubmit()
      }
    );
    this.errorEl = container.createDiv({ cls: "custom-syntax-error" });
  }
  /** (Re)build the category-dependent fields without touching common ones. */
  renderConditional() {
    const t = stringsFor(this.plugin.settings.language);
    this.conditionalEl.empty();
    this.openInput = void 0;
    this.closeInput = void 0;
    if (this.kind === "inline") {
      new import_obsidian.Setting(this.conditionalEl).setName(t.delimiter).addText((text) => {
        var _a, _b;
        this.openInput = text.inputEl;
        text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.open) != null ? _b : "++").setPlaceholder("++");
        this.openInput.addEventListener("input", () => {
          this.pendingCustomConflict = null;
          this.clearError();
        });
      });
    } else if (this.kind === "fenced") {
      new import_obsidian.Setting(this.conditionalEl).setName(t.openMarker).addText((text) => {
        var _a, _b;
        this.openInput = text.inputEl;
        text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.open) != null ? _b : ":::").setPlaceholder(t.markerPlaceholder);
      });
      new import_obsidian.Setting(this.conditionalEl).setName(t.readType).addToggle((tg) => {
        tg.setValue(this.readType);
        tg.onChange((v) => {
          this.readType = v;
        });
      });
      this.addCaptureToggle();
    } else if (this.kind === "multiline") {
      new import_obsidian.Setting(this.conditionalEl).setName(t.openMarker).addText((text) => {
        var _a, _b;
        this.openInput = text.inputEl;
        text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.open) != null ? _b : "++").setPlaceholder(t.markerPlaceholder);
      });
      new import_obsidian.Setting(this.conditionalEl).setName(t.closeMarker).addText((text) => {
        var _a, _b;
        this.closeInput = text.inputEl;
        text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.close) != null ? _b : "++").setPlaceholder(t.markerPlaceholder);
      });
      this.addCaptureToggle();
    } else {
      new import_obsidian.Setting(this.conditionalEl).setName(t.typeName).addText((text) => {
        var _a, _b;
        this.openInput = text.inputEl;
        text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.open) != null ? _b : "").setPlaceholder(t.typePlaceholder);
      });
    }
  }
  addCaptureToggle() {
    const t = stringsFor(this.plugin.settings.language);
    new import_obsidian.Setting(this.conditionalEl).setName(t.captureParams).addToggle((tg) => {
      tg.setValue(this.captureParams);
      tg.onChange((v) => {
        this.captureParams = v;
      });
    });
  }
  clearError() {
    this.errorEl.empty();
    this.errorEl.removeClass("is-visible");
  }
  showError(msg) {
    this.errorEl.empty();
    this.errorEl.createSpan({ text: msg });
    this.errorEl.addClass("is-visible");
  }
  /**
   * Validates the current input. On success returns the resolved values; on
   * failure shows the error in-place and returns `{ ok: false }`.
   */
  validate() {
    var _a, _b, _c, _d, _e;
    const t = stringsFor(this.plugin.settings.language);
    const lang = resolveLanguage(this.plugin.settings.language);
    const name = this.nameInput.value.trim();
    const css = this.cssEditor.getValue();
    const className = sanitizeClassName(this.classInput.value);
    const open = ((_b = (_a = this.openInput) == null ? void 0 : _a.value) != null ? _b : "").trim();
    const close = ((_d = (_c = this.closeInput) == null ? void 0 : _c.value) != null ? _d : "").trim();
    if (this.kind === "inline") {
      if (!open) {
        this.showError(t.delimiterRequired);
        return { ok: false };
      }
      const builtin = findBuiltinConflict(open);
      if (builtin) {
        const nm = lang === "zh" ? builtin.zh : builtin.en;
        this.showError(t.conflictBuiltin.replace("{name}", nm));
        this.pendingCustomConflict = null;
        return { ok: false };
      }
      const custom = findCustomConflict(
        open,
        this.plugin.settings.rules,
        (_e = this.rule) == null ? void 0 : _e.id
      );
      if (custom) {
        const nm = custom.name || t.untitled;
        if (this.pendingCustomConflict && this.pendingCustomConflict.id === custom.id) {
          return {
            ok: true,
            value: this.buildValue(name, "inline", open, open, false, false, css, className)
          };
        }
        this.pendingCustomConflict = custom;
        const msg = this.rule ? t.conflictCustomSave : t.conflictCustomCreate;
        this.showError(msg.replace("{name}", nm));
        return { ok: false };
      }
    } else if (this.kind === "fenced") {
      if (!open) {
        this.showError(t.delimiterRequired);
        return { ok: false };
      }
    } else if (this.kind === "multiline") {
      if (!open || !close) {
        this.showError(t.delimiterRequired);
        return { ok: false };
      }
    } else {
      if (!open) {
        this.showError(t.delimiterRequired);
        return { ok: false };
      }
    }
    const isBlock = this.kind === "fenced" || this.kind === "multiline";
    return {
      ok: true,
      value: this.buildValue(
        name,
        this.kind,
        open,
        this.kind === "inline" ? open : this.kind === "multiline" ? close : "",
        this.kind === "callout" ? true : this.kind === "fenced" ? this.readType : false,
        isBlock ? this.captureParams : false,
        css,
        className
      )
    };
  }
  buildValue(name, kind, open, close, readType, captureParams, css, className) {
    return {
      name: name || stringsFor(this.plugin.settings.language).untitled,
      kind,
      open,
      close,
      readType,
      captureParams,
      css,
      className,
      enabled: this.enabled
    };
  }
  destroy() {
    var _a;
    (_a = this.cssEditor) == null ? void 0 : _a.destroy();
  }
};
var ExportModal = class extends import_obsidian.Modal {
  constructor(app, content, emptyMessage, copyLabel, copiedLabel, failedLabel) {
    super(app);
    this.content = content;
    this.emptyMessage = emptyMessage;
    this.copyLabel = copyLabel;
    this.copiedLabel = copiedLabel;
    this.failedLabel = failedLabel;
  }
  onOpen() {
    const { contentEl } = this;
    if (!this.content) {
      contentEl.createEl("p", { text: this.emptyMessage });
      return;
    }
    const area = contentEl.createEl("textarea", {
      cls: "custom-syntax-export-area"
    });
    area.rows = 16;
    area.readOnly = true;
    area.spellcheck = false;
    area.value = this.content;
    area.setAttribute("aria-label", this.copyLabel);
    const actions = contentEl.createDiv({
      cls: "custom-syntax-modal-actions"
    });
    const copyBtn = actions.createEl("button", {
      text: this.copyLabel,
      cls: "mod-cta"
    });
    copyBtn.addEventListener("click", () => {
      area.select();
      void navigator.clipboard.writeText(this.content).then(
        () => copyBtn.setText(this.copiedLabel),
        () => copyBtn.setText(this.failedLabel)
      );
    });
  }
};
async function toggleRuleEnabled(plugin, rule, enabled) {
  rule.enabled = enabled;
  rule.conflictWithId = null;
  if (enabled) {
    for (const other of plugin.settings.rules) {
      if (other !== rule && other.enabled && delimitersConflict(rule.open, other.open)) {
        other.enabled = false;
        other.conflictWithId = rule.id;
      }
    }
  }
  await plugin.saveSettings();
}
async function deleteRule(plugin, rule) {
  plugin.settings.rules = plugin.settings.rules.filter((r) => r !== rule);
  for (const r of plugin.settings.rules) {
    if (r.conflictWithId === rule.id) {
      r.conflictWithId = null;
    }
  }
  await plugin.saveSettings();
}
function renderRuleCard(containerEl, plugin, rule, onChanged, onEdit) {
  var _a;
  const t = stringsFor(plugin.settings.language);
  const card = containerEl.createDiv({ cls: "custom-syntax-rule-card" });
  const row = card.createDiv({ cls: "custom-syntax-rule-row" });
  const badgeLabel = {
    inline: t.catInline,
    fenced: t.catFenced,
    multiline: t.catMultiline,
    callout: t.catCallout
  };
  const badge = row.createDiv({
    cls: `custom-syntax-rule-badge is-${rule.kind}`,
    text: (_a = badgeLabel[rule.kind]) != null ? _a : t.catInline
  });
  const nameEl = row.createDiv({
    cls: "custom-syntax-rule-name",
    text: rule.name || t.untitled
  });
  nameEl.title = rule.kind === "inline" ? rule.open : `${badgeLabel[rule.kind]} \xB7 ${rule.open}`;
  const controls = row.createDiv({ cls: "custom-syntax-rule-controls" });
  const editBtn = controls.createEl("button", { cls: "clickable-icon" });
  editBtn.setAttribute("aria-label", t.edit);
  (0, import_obsidian.setIcon)(editBtn, "pencil");
  editBtn.addEventListener("click", () => onEdit(rule));
  const delBtn = controls.createEl("button", { cls: "clickable-icon" });
  delBtn.setAttribute("aria-label", t.delete);
  (0, import_obsidian.setIcon)(delBtn, "trash");
  delBtn.addEventListener("click", () => {
    const name = rule.name || t.untitled;
    new ConfirmModal(
      plugin.app,
      t.deleteConfirm.replace("{name}", name),
      t.delete,
      t.cancel,
      () => {
        void deleteRule(plugin, rule).then(onChanged);
      }
    ).open();
  });
  const toggle = controls.createDiv({
    cls: rule.enabled ? "checkbox-container is-enabled" : "checkbox-container"
  });
  toggle.setAttribute("role", "switch");
  toggle.setAttribute("aria-checked", String(rule.enabled));
  toggle.setAttribute("aria-label", t.toggle);
  toggle.setAttribute("tabindex", "0");
  toggle.addEventListener("click", () => {
    const newVal = !rule.enabled;
    toggle.toggleClass("is-enabled", newVal);
    toggle.setAttribute("aria-checked", String(newVal));
    void toggleRuleEnabled(plugin, rule, newVal).then(onChanged);
  });
  toggle.addEventListener("keydown", (ev) => {
    if (ev.key === " " || ev.key === "Enter") {
      ev.preventDefault();
      toggle.click();
    }
  });
  const extraClass = sanitizeClassName(rule.className);
  if (extraClass) {
    card.createDiv({
      cls: "custom-syntax-rule-class",
      text: `.${extraClass.split(" ").join(" .")}`
    });
  }
  if (rule.conflictWithId) {
    const other = plugin.settings.rules.find(
      (r) => r.id === rule.conflictWithId
    );
    if (other) {
      card.createDiv({
        cls: "custom-syntax-rule-conflict",
        text: t.conflictAnnotation.replace(
          "{name}",
          other.name || t.untitled
        )
      });
    }
  }
}
var CustomSyntaxSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const t = stringsFor(this.plugin.settings.language);
    const nav = containerEl.createDiv({ cls: "custom-syntax-nav" });
    const title = nav.createDiv({ cls: "custom-syntax-nav-title" });
    title.createSpan({ text: t.pluginName });
    title.createSpan({
      cls: "custom-syntax-nav-version",
      text: `v${this.plugin.manifest.version}`
    });
    const groupOther = containerEl.createDiv({
      cls: "custom-syntax-settings-group"
    });
    new import_obsidian.Setting(groupOther).setName(t.other).setHeading();
    new import_obsidian.Setting(groupOther).setName(t.language).addDropdown((dd) => {
      dd.addOption("system", t.followSystem);
      dd.addOption("zh", "\u7B80\u4F53\u4E2D\u6587");
      dd.addOption("en", "English");
      dd.setValue(this.plugin.settings.language);
      dd.onChange(async (value) => {
        this.plugin.settings.language = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    new import_obsidian.Setting(groupOther).setName(t.toolbarIcon).setDesc(t.toolbarIconDesc).addToggle((tg) => {
      tg.setValue(this.plugin.settings.showRibbon);
      tg.onChange(async (value) => {
        this.plugin.settings.showRibbon = value;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian.Setting(groupOther).setName(t.invokePanel).setDesc(t.invokePanelDesc).addButton(
      (btn) => btn.setButtonText(t.openPanel).setCta().onClick(() => this.plugin.activateRulePanel())
    );
    const groupExport = containerEl.createDiv({
      cls: "custom-syntax-settings-group"
    });
    new import_obsidian.Setting(groupExport).setName(t.exportGroup).setHeading();
    new import_obsidian.Setting(groupExport).setName(t.exportName).setDesc(t.exportDesc).addButton(
      (btn) => btn.setButtonText(t.exportBtn).setCta().onClick(() => {
        new ExportModal(
          this.app,
          exportRulesAsCss(this.plugin.settings.rules),
          t.exportEmpty,
          t.copy,
          t.copied,
          t.copyFailed
        ).open();
      })
    );
    new import_obsidian.Setting(groupExport).setName(t.docs).addButton(
      (btn) => btn.setButtonText(t.docsOpen).onClick(() => {
        new DocumentationModal(this.app, this.plugin).open();
      })
    );
  }
};
var REPO_URL = "https://github.com/BAIYUMIAN/obsidian-custom-syntax";
var DocumentationModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("custom-syntax-doc");
    const t = stringsFor(this.plugin.settings.language);
    const lang = resolveLanguage(this.plugin.settings.language);
    const nav = contentEl.createDiv({ cls: "custom-syntax-doc-nav" });
    const center = nav.createDiv({ cls: "custom-syntax-doc-nav-center" });
    center.createDiv({
      cls: "custom-syntax-doc-nav-title",
      text: t.docsTitle
    });
    const repoBtn = center.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": t.docsRepo }
    });
    (0, import_obsidian.setIcon)(repoBtn, "external-link");
    repoBtn.addEventListener("click", () => {
      window.open(REPO_URL, "_blank");
    });
    const closeBtn = nav.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": t.close }
    });
    (0, import_obsidian.setIcon)(closeBtn, "x");
    closeBtn.addEventListener("click", () => this.close());
    const body = contentEl.createDiv({ cls: "custom-syntax-doc-body" });
    const sections = lang === "zh" ? [
      {
        h: "\u6982\u8FF0",
        p: [
          "\u81EA\u5B9A\u4E49\u8BED\u6CD5\u8BA9\u4F60\u5B9A\u4E49\u81EA\u5DF1\u7684 Markdown \u6807\u8BB0\uFF0C\u5E76\u7528\u81EA\u6709 CSS \u6E32\u67D3\u3002\u5B83\u53EA\u5728\u7F16\u8F91\u5668\u4E0E\u9605\u8BFB\u89C6\u56FE\u505A\u89C6\u89C9\u88C5\u9970\uFF0C\u6C38\u4E0D\u6539\u5199\u4F60\u7684\u6E90\u6587\u4EF6\u3002",
          "\u7F16\u8F91\u5668\uFF08\u5B9E\u65F6\u9884\u89C8/\u6E90\u7801\u6A21\u5F0F\uFF09\u901A\u8FC7 CodeMirror \u88C5\u9970\u5B9E\u73B0\uFF0C\u9605\u8BFB\u89C6\u56FE\u901A\u8FC7 Markdown \u540E\u5904\u7406\u5668\u5B9E\u73B0\u2014\u2014\u4E24\u6761\u90FD\u662F\u5B98\u65B9\u7A33\u5B9A\u6269\u5C55\u70B9\u3002"
        ]
      },
      {
        h: "\u6DFB\u52A0\u89C4\u5219",
        p: [
          "\u5728\u53F3\u4FA7\u8FB9\u680F\u89C4\u5219\u7BA1\u7406\u5668\u70B9\u300C\u6DFB\u52A0\u89C4\u5219\u300D\uFF0C\u6216\u5728\u8BBE\u7F6E\u91CC\u70B9\u300C\u6253\u5F00\u9762\u677F\u300D\u3002",
          "\u5148\u9009\u300C\u8BED\u6CD5\u7C7B\u522B\u300D\uFF0C\u518D\u586B\u5BF9\u5E94\u6807\u8BB0\uFF0C\u7136\u540E\u5728\u300C\u6837\u5F0F\u58F0\u660E\u300D\u91CC\u53EA\u5199 CSS \u82B1\u62EC\u53F7\u91CC\u7684\u5185\u5BB9\uFF1A"
        ],
        code: "border: 1px solid var(--interactive-accent);\nborder-radius: 6px;\npadding: 1px 5px;"
      },
      {
        h: "\u56DB\u7C7B\u8BED\u6CD5",
        p: [
          "\u884C\u5185\u914D\u5BF9\uFF1A\u7528\u6210\u5BF9\u5206\u9694\u7B26\u5305\u88F9\u540C\u4E00\u884C\u6587\u5B57\uFF0C\u4F8B\u5982 ++\u6587\u5B57++\u3002",
          "\u56F4\u680F\u5757\uFF1APandoc \u5F0F :::\u7C7B\u578B \u2026 ::: \u5BB9\u5668\u5757\uFF0C\u72EC\u5360\u6210\u884C\u3002",
          "\u591A\u884C\u5757\uFF1A\u8D77\u59CB\u6807\u8BB0\u72EC\u5360\u4E00\u884C\uFF0C\u7ED3\u675F\u6807\u8BB0\u4E5F\u72EC\u5360\u4E00\u884C\uFF0C\u4F8B\u5982\u7528 ++ \u5305\u4F4F\u591A\u884C\u5185\u5BB9\u3002",
          "\u81EA\u5B9A\u4E49 Callout\uFF1A\u7528 > [!\u7C7B\u578B] \u89E6\u53D1\uFF0C\u76D2\u5B50\u7531 Obsidian \u539F\u751F\u6E32\u67D3\uFF0C\u6211\u4EEC\u4EC5\u52A0\u6837\u5F0F\u3002"
        ],
        code: "++\u884C\u5185\u6587\u5B57++\n\n:::note\n\u8FD9\u662F\u56F4\u680F\u5757\n:::\n\n++\n\u8FD9\u662F\u591A\u884C\u5757\n\u8DE8\u4E24\u884C\n++\n\n> [!mynote]\n\u8FD9\u662F\u81EA\u5B9A\u4E49 callout"
      },
      {
        h: "\u8BFB\u53D6\u7C7B\u578B",
        p: [
          "\u56F4\u680F\u5757\u4E0E Callout \u53EF\u5F00\u542F\u300C\u8BFB\u53D6\u7C7B\u578B\u300D\uFF1A\u8D77\u59CB\u884C\u7684\u7C7B\u578B\uFF08\u5982 note / mynote\uFF09\u4F1A\u4F5C\u4E3A\u7C7B\u540D\u94A9\u5B50\uFF0C\u8BA9 CSS \u7247\u6BB5\u6309\u7C7B\u578B\u7CBE\u786E\u5B9A\u5236\u3002",
          '\u4F8B\u5982 :::note \u4F1A\u83B7\u5F97 .cs-fence-note \u7C7B\uFF0C> [!mynote] \u5BF9\u5E94\u539F\u751F data-callout="mynote"\u3002'
        ]
      },
      {
        h: "\u6355\u83B7\u53C2\u6570",
        p: [
          "\u5F00\u542F\u300C\u6355\u83B7\u53C2\u6570\u300D\u540E\uFF0C\u53EF\u5728\u6807\u8BB0\u540E\u5199 { .\u7C7B\u540D #id \u952E=\u503C }\uFF0C\u52A8\u6001\u5957\u7528\u6837\u5F0F\u3002",
          ".\u7C7B\u540D \u52A0 class\uFF0C#id \u8BBE\u5143\u7D20 id\uFF0C\u952E=\u503C \u8F6C\u4E3A\u5185\u8054 CSS\uFF08\u5982 color=red\uFF09\u3002"
        ],
        code: ":::note { .box #main color=red }\n\u5E26\u53C2\u6570\u7684\u56F4\u680F\u5757\n:::"
      },
      {
        h: "\u7C7B\u6837\u5F0F\u590D\u7528\uFF08\u53EF\u9009\uFF09",
        p: [
          "\u5728\u300C\u7C7B\u540D\u300D\u91CC\u586B\u4E00\u4E2A\u6216\u591A\u4E2A CSS \u7C7B\u540D\uFF08\u7A7A\u683C\u5206\u9694\uFF09\u3002\u5F53\u300C\u6837\u5F0F\u58F0\u660E\u300D\u7559\u7A7A\u65F6\uFF0C\u6837\u5F0F\u5B8C\u5168\u7531\u4F60\u81EA\u5DF1\u7684 CSS \u7247\u6BB5\u4E2D\u4E3A\u8BE5\u7C7B\u5199\u7684\u89C4\u5219\u51B3\u5B9A\uFF0C\u4ECE\u800C\u80FD\u88AB\u4E3B\u9898\u590D\u7528\u4E0E\u8986\u76D6\u3002",
          "\u6BCF\u6761\u89C4\u5219\u8FD8\u81EA\u5E26\u7A33\u5B9A\u7C7B\u540D .cs-block-<id>\uFF08\u5757\u7EA7\uFF09\u6216 .custom-syntax-<id>-content\uFF08\u884C\u5185\uFF09\uFF0C\u4FBF\u4E8E\u7CBE\u786E\u5B9A\u4F4D\u3002"
        ]
      },
      {
        h: "\u5BFC\u51FA CSS \u7247\u6BB5",
        p: [
          "\u5728\u8BBE\u7F6E\u300C\u5BFC\u51FA\u300D\u7EC4\u70B9\u300C\u5BFC\u51FA CSS \u7247\u6BB5\u300D\uFF0C\u628A\u73B0\u6709\u89C4\u5219\u6837\u5F0F\u5BFC\u51FA\u4E3A .css \u6587\u4EF6\uFF0C\u653E\u5165\u7247\u6BB5\u6587\u4EF6\u5939\u5373\u53EF\u957F\u671F\u590D\u7528\u3002"
        ]
      },
      {
        h: "\u9605\u8BFB\u6A21\u5F0F\u884C\u4E3A",
        p: [
          "\u5206\u9694\u7B26\u5185\u4E3A\u7A7A\uFF08\u4F8B\u5982 ++++\uFF09\u65F6\uFF0C\u5F53\u4F5C\u666E\u901A\u6587\u672C\uFF0C\u4E0D\u505A\u4EFB\u4F55\u6E32\u67D3\u2014\u2014\u8FD9\u548C\u539F\u751F == \u5904\u7406 ==== \u7684\u65B9\u5F0F\u4E00\u81F4\u3002",
          "\u4EE3\u7801\u5757\u3001\u884C\u5185\u4EE3\u7801\u3001\u516C\u5F0F\u4E0E\u94FE\u63A5\u5185\u90E8\u4E0D\u4F1A\u6E32\u67D3\uFF0C\u4FDD\u62A4\u539F\u6709\u8BED\u4E49\u3002"
        ]
      },
      {
        h: "\u8BED\u4E49\u7D22\u5F15\u4E0E\u4F34\u751F\u6587\u4EF6\uFF08\u5B9E\u9A8C\u6027\uFF09",
        p: [
          "\u63D2\u4EF6\u5728\u300C\u6253\u5F00/\u7F16\u8F91\u300D\u7B14\u8BB0\u65F6\u61D2\u52A0\u8F7D\u5EFA\u7ACB\u81EA\u6709\u7D22\u5F15\uFF0C\u8BB0\u5F55\u6BCF\u6761\u89C4\u5219\u5728\u4F55\u5904\u5339\u914D\uFF0C\u53EF\u901A\u8FC7\u63D2\u4EF6\u5B9E\u4F8B\u7684 syntaxIndex API \u88AB\u5176\u4ED6\u63D2\u4EF6\u8BFB\u53D6\u2014\u2014\u4E0D\u4FEE\u6539 Obsidian \u5143\u6570\u636E\u7F13\u5B58\u3002",
          "\u547D\u4EE4\u9762\u677F\u4E2D\u7684\u300CGenerate syntax metadata companion\u300D\u4F1A\u4E3A\u5F53\u524D\u7B14\u8BB0\u751F\u6210 <\u7B14\u8BB0\u540D>.cs-meta.md \u4F34\u751F\u6587\u4EF6\uFF0C\u5185\u542B Dataview \u53EF\u8BFB\u7684\u5185\u8054\u5B57\u6BB5\uFF0C\u4F7F\u81EA\u5B9A\u4E49\u6807\u8BB0\u53EF\u88AB Dataview \u67E5\u8BE2\u3002\u8BE5\u6587\u4EF6\u4E3A\u989D\u5916\u751F\u6210\uFF0C\u53EF\u6309\u9700\u5220\u9664\u3002"
        ]
      },
      {
        h: "\u5DF2\u77E5\u9650\u5236",
        p: [
          "\u672C\u63D2\u4EF6\u53EA\u505A\u89C6\u89C9\u88C5\u9970\uFF0C\u4E0D\u65B0\u589E\u771F\u6B63\u7684 Markdown AST \u8282\u70B9\uFF1B\u590D\u5236\u5230 Typora\u3001Pandoc \u5BFC\u51FA\u65F6\u5206\u9694\u7B26\u539F\u6837\u4FDD\u7559\u3002",
          "\u5D4C\u5957\u5757\u7EA7\u8BED\u6CD5\u4E3A\u6709\u9650\u652F\u6301\uFF1B\u4EE3\u7801\u5757/\u516C\u5F0F\u5185\u90E8\u4E0D\u6E32\u67D3\u3002",
          "\u300C\u53EF\u89C6\u5316\u7F16\u8F91\u300D\u6309\u94AE\u4E3A\u5360\u4F4D\uFF0C\u5C1A\u672A\u5F00\u653E\u3002"
        ]
      }
    ] : [
      {
        h: "Overview",
        p: [
          "Custom Syntax lets you define your own Markdown markers and style them with your own CSS. It only decorates the editor and reading view \u2014 it never rewrites your source.",
          "Live Preview / Source mode uses CodeMirror decorations; reading view uses a Markdown post-processor. Both are official, stable extension points."
        ]
      },
      {
        h: "Add a rule",
        p: [
          'Click "Add rule" in the right-sidebar rule manager, or "Open panel" in the settings.',
          "Pick a syntax category, fill in the marker, then write only what goes inside the CSS curly braces:"
        ],
        code: "border: 1px solid var(--interactive-accent);\nborder-radius: 6px;\npadding: 1px 5px;"
      },
      {
        h: "The four syntax shapes",
        p: [
          "Inline pair: a delimiter wrapping text on the same line, e.g. ++text++.",
          "Fenced block: a Pandoc-style :::type \u2026 ::: container, on its own lines.",
          "Multiline block: a marker alone on its line opens, the same marker alone on a later line closes, e.g. ++ around several lines.",
          "Custom callout: > [!type] triggers a box rendered natively by Obsidian; we only add styling."
        ],
        code: "++inline text++\n\n:::note\nThis is a fenced block\n:::\n\n++\nThis is a multiline block\nspanning two lines\n++\n\n> [!mynote]\nThis is a custom callout"
      },
      {
        h: "Read type",
        p: [
          "Fenced blocks and callouts can read the type from the opening line (e.g. note / mynote) and expose it as a class hook, so a CSS snippet can target a type precisely.",
          'For example :::note gets the .cs-fence-note class; > [!mynote] maps to the native data-callout="mynote".'
        ]
      },
      {
        h: "Capture parameters",
        p: [
          'With "Capture parameters" on, write { .class #id key=value } after the marker to apply styles dynamically.',
          ".class adds a class, #id sets the element id, key=value becomes inline CSS (e.g. color=red)."
        ],
        code: ":::note { .box #main color=red }\nA fenced block with parameters\n:::"
      },
      {
        h: "Class-based styling (optional)",
        p: [
          'Fill in one or more CSS class names (space-separated) under "Class name". When declarations are left empty, styling comes entirely from your own CSS snippet for that class, so it can be reused and overridden by themes.',
          "Every rule also carries a stable class \u2014 .cs-block-<id> (blocks) or .custom-syntax-<id>-content (inline) \u2014 for precise targeting."
        ]
      },
      {
        h: "Export as CSS snippet",
        p: [
          `Under the settings "Export" group, click "Export CSS snippet" to export your rules' styles as a .css file you can drop into your snippets folder.`
        ]
      },
      {
        h: "Reading view",
        p: [
          "A delimiter with nothing inside (e.g. ++++) is left as plain text and not rendered \u2014 like how native == leaves ==== alone.",
          "Code blocks, inline code, math and links are never decorated, preserving their meaning."
        ]
      },
      {
        h: "Semantic index & companion (experimental)",
        p: [
          "As you open or edit a note, the plugin lazily builds its own index of where each rule matched. Other plugins can read it through the plugin instance's syntaxIndex API \u2014 the Obsidian metadata cache is never patched.",
          'The command palette command "Generate syntax metadata companion" writes a <note>.cs-meta.md companion next to the current note, with Dataview-readable inline fields so custom markers become queryable. The companion is an extra file you can delete at any time.'
        ]
      },
      {
        h: "Known limitations",
        p: [
          "This plugin only decorates \u2014 it does not add real Markdown AST nodes, and when you copy to Typora or export via Pandoc the delimiters are kept as-is.",
          "Nested block syntax has limited support; code blocks and math are never rendered.",
          'The "Visual editor" button is a placeholder and is not yet available.'
        ]
      }
    ];
    for (const s of sections) {
      body.createEl("h3", { cls: "custom-syntax-doc-h", text: s.h });
      for (const para of s.p) {
        body.createEl("p", { cls: "custom-syntax-doc-p", text: para });
      }
      if (s.code !== void 0) {
        body.createEl("pre", {
          cls: "custom-syntax-doc-code",
          text: s.code
        });
      }
    }
  }
  onClose() {
    this.contentEl.empty();
  }
};
var LanguageModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("custom-syntax-lang");
    const t = stringsFor(this.plugin.settings.language);
    const nav = contentEl.createDiv({ cls: "custom-syntax-lang-nav" });
    nav.createDiv({
      cls: "custom-syntax-lang-nav-title",
      text: t.languageSwitch
    });
    const body = contentEl.createDiv({ cls: "custom-syntax-lang-body" });
    const options = [
      { value: "system", label: t.followSystem },
      { value: "zh", label: "\u7B80\u4F53\u4E2D\u6587" },
      { value: "en", label: "English" }
    ];
    for (const opt of options) {
      const row = body.createDiv({ cls: "custom-syntax-lang-row" });
      row.createSpan({ text: opt.label });
      const radio = row.createSpan({ cls: "custom-syntax-lang-radio" });
      if (this.plugin.settings.language === opt.value) {
        radio.addClass("is-selected");
      }
      row.addEventListener("click", () => this.select(opt.value));
    }
  }
  select(value) {
    this.plugin.settings.language = value;
    void this.plugin.saveSettings().then(() => this.close());
  }
  onClose() {
    this.contentEl.empty();
  }
};

// src/editorExtension.ts
function collectCodeRanges(view) {
  const ranges = [];
  try {
    for (const { from, to } of view.visibleRanges) {
      (0, import_language3.syntaxTree)(view.state).iterate({
        from,
        to,
        enter(node) {
          const name = node.name.toLowerCase();
          if (name.includes("code") || name.includes("comment") || name.includes("math") || name.includes("html")) {
            ranges.push({ from: node.from, to: node.to });
            return false;
          }
        }
      });
    }
  } catch (e) {
    return [];
  }
  return ranges;
}
function isInCode(from, to, ranges) {
  for (const r of ranges) {
    if (from < r.to && to > r.from) {
      return true;
    }
  }
  return false;
}
function buildDecorations(view, rules) {
  var _a, _b;
  const decos = [];
  const codeRanges = collectCodeRanges(view);
  const scanRanges = view.visibleRanges.length > 0 ? view.visibleRanges : [{ from: 0, to: view.state.doc.length }];
  const sel = view.state.selection.main;
  for (const rule of rules) {
    if (!rule.enabled || rule.kind !== "inline" || !rule.open) {
      continue;
    }
    const css = ((_a = rule.css) != null ? _a : "").trim();
    const extraClass = ((_b = rule.className) != null ? _b : "").trim();
    if (!css && !extraClass) {
      continue;
    }
    const contentCls = contentClasses(rule);
    const delim = rule.open;
    const re = new RegExp(
      `${escapeRegExp(delim)}([^\\n]*?)${escapeRegExp(delim)}`,
      "g"
    );
    const delimCls = ruleClassName(rule.id) + "-delim";
    for (const { from, to } of scanRanges) {
      const text = view.state.sliceDoc(from, to);
      re.lastIndex = 0;
      let m;
      while ((m = re.exec(text)) !== null) {
        const content = m[1];
        if (content.length === 0) {
          continue;
        }
        const fullStart = from + m.index;
        const contentStart = fullStart + delim.length;
        const contentEnd = contentStart + content.length;
        const fullEnd = fullStart + m[0].length;
        if (isInCode(fullStart, fullEnd, codeRanges)) {
          continue;
        }
        const active = sel.from <= fullEnd && sel.to >= fullStart;
        if (active) {
          decos.push(
            import_view2.Decoration.mark({
              class: delimCls
            }).range(fullStart, contentStart)
          );
        } else {
          decos.push(
            import_view2.Decoration.replace({}).range(fullStart, contentStart)
          );
        }
        decos.push(
          import_view2.Decoration.mark({
            class: contentCls,
            // Declarations ride along only when the user wrote any;
            // an empty field means a CSS snippet owns the styling.
            attributes: css ? { style: css } : void 0
          }).range(contentStart, contentEnd)
        );
        if (active) {
          decos.push(
            import_view2.Decoration.mark({
              class: delimCls
            }).range(contentEnd, fullEnd)
          );
        } else {
          decos.push(
            import_view2.Decoration.replace({}).range(contentEnd, fullEnd)
          );
        }
      }
    }
  }
  for (const rule of rules) {
    if (!rule.enabled) continue;
    if (rule.kind !== "fenced" && rule.kind !== "multiline") continue;
    const open = rule.open;
    const close = rule.close || open;
    if (!open) continue;
    const markerCls = `cs-block-marker cs-block-marker-${rule.id}`;
    for (const { from, to } of scanRanges) {
      const text = view.state.sliceDoc(from, to);
      let lineStart = 0;
      let idx = 0;
      while (idx <= text.length) {
        const nl = text.indexOf("\n", idx);
        const lineEnd = nl === -1 ? text.length : nl;
        const trimmed = text.slice(lineStart, lineEnd).trim();
        const isMarker = rule.kind === "fenced" ? trimmed.startsWith(open) : trimmed === open || trimmed === close;
        if (isMarker && !isInCode(from + lineStart, from + lineEnd, codeRanges)) {
          decos.push(
            import_view2.Decoration.line({ class: markerCls }).range(from + lineStart)
          );
        }
        if (nl === -1) break;
        idx = nl + 1;
        lineStart = idx;
      }
    }
  }
  return import_view2.Decoration.set(decos, true);
}
function createEditorExtension(getRules) {
  class CustomSyntaxView {
    constructor(view) {
      this.decorations = buildDecorations(view, getRules());
    }
    update(update) {
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = buildDecorations(update.view, getRules());
      }
    }
    destroy() {
    }
  }
  const spec = {
    decorations: (value) => value.decorations
  };
  return import_view2.ViewPlugin.fromClass(CustomSyntaxView, spec);
}

// src/postProcessor.ts
function shouldSkip(node) {
  let el = node.parentElement;
  while (el) {
    const tag = el.tagName;
    if (tag === "CODE" || tag === "PRE" || tag === "A" || tag === "MATH" || tag === "SCRIPT" || tag === "STYLE") {
      return true;
    }
    el = el.parentElement;
  }
  return false;
}
function cssToRecord(css) {
  const result = {};
  for (const decl of css.split(";")) {
    const trimmed = decl.trim();
    if (!trimmed) continue;
    const idx = trimmed.indexOf(":");
    if (idx === -1) continue;
    const prop = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim();
    if (prop && value) {
      result[prop] = value;
    }
  }
  return result;
}
function sanitizeType(raw) {
  return (raw != null ? raw : "").split(/[\s]+/).map((t) => t.trim()).filter((t) => /^-?[A-Za-z_][A-Za-z0-9_-]*$/.test(t)).join("-");
}
function blockRuleClasses(rule, type) {
  const parts = ["cs-block", `cs-block-${rule.id}`];
  if (type) {
    parts.push(`cs-fence-${sanitizeType(type)}`);
  }
  const extra = sanitizeClassName(rule.className);
  if (extra) {
    parts.push(extra);
  }
  return parts.join(" ");
}
function parseParams(raw) {
  const result = { classes: [], style: {} };
  const inner = raw.trim().replace(/^\{|\}$/g, "").trim();
  if (!inner) {
    return result;
  }
  for (const token of inner.split(/\s+/)) {
    if (!token) continue;
    if (token.startsWith(".")) {
      const cls = sanitizeClassName(token.slice(1));
      if (cls) result.classes.push(cls);
    } else if (token.startsWith("#")) {
      const id = token.slice(1);
      if (/^-?[A-Za-z_][A-Za-z0-9_-]*$/.test(id)) {
        result.id = id;
      }
    } else {
      const eq = token.indexOf("=");
      if (eq > 0) {
        const prop = token.slice(0, eq).trim();
        const value = token.slice(eq + 1).trim();
        if (prop && value && /^[A-Za-z-]+$/.test(prop)) {
          result.style[prop] = value;
        }
      }
    }
  }
  return result;
}
function applyParams(el, params) {
  if (!params) return;
  if (params.classes.length) {
    el.addClasses(params.classes);
  }
  if (params.id) {
    el.id = params.id;
  }
  if (Object.keys(params.style).length) {
    el.setCssStyles(params.style);
  }
}
function applyRule(root, rule) {
  if (!rule.enabled) {
    return;
  }
  switch (rule.kind) {
    case "inline":
      applyInline(root, rule);
      break;
    case "fenced":
    case "multiline":
      applyBlock(root, rule);
      break;
    case "callout":
      applyCallout(root, rule);
      break;
  }
}
function applyInline(root, rule) {
  var _a, _b, _c, _d, _e;
  const open = rule.open;
  if (!open) {
    return;
  }
  const css = ((_a = rule.css) != null ? _a : "").trim();
  if (!css && !((_b = rule.className) != null ? _b : "").trim()) {
    return;
  }
  const head = rule.captureParams ? `${escapeRegExp(open)}\\s*(\\{[^}]*\\})?\\s*([^\\n]*?)` : `${escapeRegExp(open)}([^\\n]*?)`;
  const re = new RegExp(head + escapeRegExp(open), "g");
  const cssRecord = css ? cssToRecord(css) : null;
  const classes = contentClasses(rule);
  const doc = root.ownerDocument;
  const walker = doc.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  while (walker.nextNode()) {
    const node = walker.currentNode;
    if (shouldSkip(node)) {
      continue;
    }
    if (((_c = node.nodeValue) != null ? _c : "").length === 0) {
      continue;
    }
    textNodes.push(node);
  }
  for (const node of textNodes) {
    const text = (_d = node.nodeValue) != null ? _d : "";
    if (!re.test(text)) {
      re.lastIndex = 0;
      continue;
    }
    re.lastIndex = 0;
    const fragment = createFragment();
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m.index > lastIndex) {
        fragment.appendChild(
          doc.createTextNode(text.slice(lastIndex, m.index))
        );
      }
      const paramsRaw = rule.captureParams ? m[1] : void 0;
      const content = rule.captureParams ? m[2] : m[1];
      if ((content != null ? content : "").length === 0) {
        lastIndex = m.index + m[0].length;
        continue;
      }
      const span = createSpan();
      span.addClasses(classes.split(" "));
      if (cssRecord) {
        span.setCssStyles(cssRecord);
      }
      if (paramsRaw) {
        applyParams(span, parseParams(paramsRaw));
      }
      span.textContent = content;
      fragment.appendChild(span);
      lastIndex = m.index + m[0].length;
      if (m[0].length === 0) {
        re.lastIndex++;
      }
    }
    if (lastIndex < text.length) {
      fragment.appendChild(doc.createTextNode(text.slice(lastIndex)));
    }
    if (fragment.childNodes.length > 0) {
      (_e = node.parentNode) == null ? void 0 : _e.replaceChild(fragment, node);
    }
  }
}
function matchOpener(el, rule) {
  const first = firstLineText(el);
  if (first === null) return null;
  const open = rule.open;
  if (rule.kind === "fenced") {
    if (!first.startsWith(open)) return null;
    const tail = first.slice(open.length);
    let type;
    let params = null;
    if (rule.captureParams) {
      const bs = tail.indexOf("{");
      if (bs >= 0) {
        const be = tail.indexOf("}", bs);
        if (be >= 0) {
          params = parseParams(tail.slice(bs, be + 1));
          type = rule.readType ? tail.slice(0, bs).trim() || void 0 : void 0;
        } else {
          type = rule.readType ? tail.trim() : void 0;
        }
      } else {
        type = rule.readType ? tail.trim() : void 0;
      }
    } else {
      type = rule.readType ? tail.trim() : void 0;
    }
    return { type, params };
  }
  if (first === open) {
    return { params: null };
  }
  if (rule.captureParams && first.startsWith(open) && /\{/.test(first.slice(open.length))) {
    return { params: parseTrailingParams(first.slice(open.length)) };
  }
  return null;
}
function parseTrailingParams(tail) {
  const m = tail.trim().match(/^\{(\{[^}]*\}|[^}]*)\}/);
  if (!m) return null;
  return parseParams(m[0]);
}
function firstLineText(el) {
  var _a, _b;
  let buf = "";
  for (const node of Array.from(el.childNodes)) {
    if (node.nodeName === "BR") {
      if (buf) return buf;
      buf = "";
      continue;
    }
    if (node.nodeType === Node.TEXT_NODE) {
      const parts = ((_a = node.nodeValue) != null ? _a : "").split("\n");
      for (let i = 0; i < parts.length; i++) {
        if (i > 0 && (buf || i > 1 || true)) {
          if (buf) return buf;
          buf = "";
        }
        buf += parts[i];
      }
    } else {
      buf += (_b = node.textContent) != null ? _b : "";
    }
  }
  return buf === "" && el.childNodes.length === 0 ? null : buf;
}
function lineText(el) {
  var _a;
  return ((_a = el.textContent) != null ? _a : "").replace(/\n/g, " ").trim();
}
function splitElementByBr(el) {
  var _a;
  const doc = el.ownerDocument;
  const lines = [[]];
  for (const node of Array.from(el.childNodes)) {
    if (node.nodeName === "BR") {
      lines.push([]);
      continue;
    }
    if (node.nodeType === Node.TEXT_NODE) {
      const parts = ((_a = node.nodeValue) != null ? _a : "").split("\n");
      for (let i = 0; i < parts.length; i++) {
        if (i > 0) lines.push([]);
        if (parts[i]) lines[lines.length - 1].push(doc.createTextNode(parts[i]));
      }
    } else {
      lines[lines.length - 1].push(node);
    }
  }
  const created = [];
  for (const lineNodes of lines) {
    const p = doc.createElement("p");
    for (const n of lineNodes) p.appendChild(n);
    created.push(p);
  }
  const parent = el.parentElement;
  if (!parent) return created;
  let ref = el;
  for (const p of created) {
    parent.insertBefore(p, ref);
    ref = p;
  }
  parent.removeChild(el);
  return created;
}
function applyBlock(root, rule) {
  var _a, _b;
  const open = rule.open;
  if (!open) return;
  const close = rule.close || open;
  if (root.dataset.csBlock) return;
  const parent = root.parentElement;
  if (!parent) return;
  const opener = matchOpener(root, rule);
  if (!opener) return;
  const openerLines = root.querySelector("br") || /\n/.test((_a = root.textContent) != null ? _a : "") ? splitElementByBr(root) : [root];
  const openerEl = openerLines[0];
  const siblings = Array.from(parent.children);
  const lastIdx = siblings.indexOf(openerLines[openerLines.length - 1]);
  const restEls = [
    ...openerLines.slice(1),
    ...siblings.slice(lastIdx + 1)
  ];
  let closerIdx = -1;
  for (let i = 0; i < restEls.length; i++) {
    if (restEls[i].dataset.csBlock) break;
    if (lineText(restEls[i]) === close) {
      closerIdx = i;
      break;
    }
  }
  if (closerIdx === -1) {
    return;
  }
  const contentEls = restEls.slice(0, closerIdx);
  const closerEl = restEls[closerIdx];
  if (contentEls.length === 0) {
  }
  const doc = root.ownerDocument;
  const wrapper = doc.createElement("div");
  wrapper.className = blockRuleClasses(rule, opener.type);
  wrapper.dataset.csBlock = rule.id;
  openerEl.dataset.csBlock = "x";
  closerEl.dataset.csBlock = "x";
  for (const c of contentEls) c.dataset.csBlock = "x";
  const css = ((_b = rule.css) != null ? _b : "").trim();
  if (css) {
    wrapper.setCssStyles(cssToRecord(css));
  }
  applyParams(wrapper, opener.params);
  for (const c of contentEls) {
    while (c.firstChild) {
      wrapper.appendChild(c.firstChild);
    }
  }
  parent.insertBefore(wrapper, openerEl);
  parent.removeChild(openerEl);
  for (const c of contentEls) {
    parent.removeChild(c);
  }
  parent.removeChild(closerEl);
}
function applyCallout(root, rule) {
  var _a;
  const type = rule.open;
  if (!type) {
    return;
  }
  const targets = [];
  if (root.matches(".callout")) {
    targets.push(root);
  }
  root.querySelectorAll(".callout").forEach(
    (n) => targets.push(n)
  );
  for (const el of targets) {
    if (el.getAttribute("data-callout") !== type) {
      continue;
    }
    const css = ((_a = rule.css) != null ? _a : "").trim();
    if (css) {
      el.setCssStyles(cssToRecord(css));
    }
    const extra = sanitizeClassName(rule.className);
    if (extra) {
      el.addClasses(extra.split(" "));
    }
  }
}

// src/syntaxIndex.ts
var SyntaxIndex = class {
  constructor() {
    this.map = /* @__PURE__ */ new Map();
  }
  /** (Re)build the index entry for one file path. */
  indexFile(path, content, rules) {
    this.map.set(path, scanContent(content, rules));
  }
  removeFile(path) {
    this.map.delete(path);
  }
  getForPath(path) {
    var _a;
    return (_a = this.map.get(path)) != null ? _a : [];
  }
  getAll() {
    return Object.fromEntries(this.map);
  }
  size() {
    return this.map.size;
  }
};
function scanContent(content, rules) {
  const out = [];
  const lines = content.split(/\r?\n/);
  for (const rule of rules) {
    if (!rule.enabled || !rule.open) continue;
    if (rule.kind === "inline") {
      scanInline(lines, rule, out);
    } else if (rule.kind === "callout") {
      scanCallout(lines, rule, out);
    } else {
      scanBlock(lines, rule, out);
    }
  }
  return out;
}
function scanInline(lines, rule, out) {
  const head = rule.captureParams ? `${escapeRegExp(rule.open)}\\s*(\\{[^}]*\\})?\\s*([^\\n]*?)` : `${escapeRegExp(rule.open)}([^\\n]*?)`;
  const re = new RegExp(head + escapeRegExp(rule.open), "g");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    re.lastIndex = 0;
    let m;
    while ((m = re.exec(line)) !== null) {
      const content = rule.captureParams ? m[2] : m[1];
      if (!content) continue;
      out.push({
        ruleId: rule.id,
        ruleName: rule.name,
        kind: "inline",
        marker: rule.open,
        params: rule.captureParams ? m[1] : void 0,
        line: i + 1,
        excerpt: content.slice(0, 80)
      });
    }
  }
}
function scanBlock(lines, rule, out) {
  const open = rule.open;
  const close = rule.close || open;
  let openLine = -1;
  let type;
  let params;
  for (let i = 0; i < lines.length; i++) {
    const trimmed = lines[i].trim();
    if (openLine === -1) {
      if (rule.kind === "fenced" ? trimmed.startsWith(open) : trimmed === open) {
        openLine = i;
        const tail = lines[i].slice(open.length);
        if (rule.captureParams) {
          const bs = tail.indexOf("{");
          const be = tail.indexOf("}", bs);
          if (bs >= 0 && be > bs) {
            params = tail.slice(bs, be + 1);
            type = rule.readType ? tail.slice(0, bs).trim() || void 0 : void 0;
          } else {
            type = rule.readType ? tail.trim() : void 0;
          }
        } else {
          type = rule.readType ? tail.trim() : void 0;
        }
      }
    } else if (trimmed === close) {
      out.push({
        ruleId: rule.id,
        ruleName: rule.name,
        kind: rule.kind,
        marker: rule.open,
        type,
        params,
        line: openLine + 1,
        excerpt: `${lines[openLine].trim()} \u2026 ${trimmed}`
      });
      openLine = -1;
      type = void 0;
      params = void 0;
    }
  }
}
function scanCallout(lines, rule, out) {
  const re = /^>\s*\[!\s*([^\]\s]+)\s*\]/;
  for (let i = 0; i < lines.length; i++) {
    const m = lines[i].match(re);
    if (m && m[1] === rule.open) {
      out.push({
        ruleId: rule.id,
        ruleName: rule.name,
        kind: "callout",
        marker: `> [!${rule.open}]`,
        type: rule.open,
        line: i + 1,
        excerpt: lines[i].trim()
      });
    }
  }
}
function buildCompanion(noteName, occ) {
  const rows = occ.map(
    (o) => `cs-rule:: ${o.ruleName}
cs-kind:: ${o.kind}
cs-line:: ${o.line}` + (o.type ? `
cs-type:: ${o.type}` : "")
  ).join("\n\n");
  const body = [
    "---",
    "custom-syntax: true",
    "---",
    "",
    `# Custom Syntax index \u2014 ${noteName}`,
    "",
    "> Generated by the Custom Syntax plugin. Each block below is a Dataview-readable",
    "> inline field describing where a custom rule matched in the source note.",
    "",
    occ.length === 0 ? "_No custom-syntax matches found in this note._" : rows,
    ""
  ].join("\n");
  return body;
}

// src/rulePanel.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_RULE_PANEL = "custom-syntax-rule-panel";
var RulePanelView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.mode = "list";
    this.editing = null;
    this.form = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_RULE_PANEL;
  }
  getDisplayText() {
    return stringsFor(this.plugin.settings.language).pluginName;
  }
  getIcon() {
    return "braces";
  }
  async onOpen() {
    this.rebuild();
  }
  async onClose() {
    var _a;
    (_a = this.form) == null ? void 0 : _a.destroy();
    this.form = null;
  }
  /** Rebuild the visible page from the current `mode`. */
  rebuild() {
    if (this.mode === "editor" && this.form) {
      return;
    }
    const root = this.contentEl;
    root.empty();
    root.addClass("custom-syntax-panel");
    const t = stringsFor(this.plugin.settings.language);
    if (this.mode === "list") {
      this.renderList(root, t);
    } else {
      this.renderEditor(root, t);
    }
  }
  renderList(root, t) {
    const nav = root.createDiv({ cls: "custom-syntax-panel-nav" });
    const title = nav.createDiv({ cls: "custom-syntax-panel-nav-title" });
    title.createSpan({ text: t.pluginName });
    title.createSpan({
      cls: "custom-syntax-nav-version",
      text: `v${this.plugin.manifest.version}`
    });
    const newBtn = nav.createEl("button", {
      text: t.addRule,
      cls: "mod-cta"
    });
    newBtn.addEventListener("click", () => this.openEditor(null));
    const body = root.createDiv({
      cls: "custom-syntax-panel-body custom-syntax-rules"
    });
    if (this.plugin.settings.rules.length === 0) {
      body.createDiv({ cls: "custom-syntax-empty", text: t.noRules });
    } else {
      this.plugin.settings.rules.forEach((rule) => {
        renderRuleCard(
          body,
          this.plugin,
          rule,
          () => this.rebuild(),
          (r) => this.openEditor(r)
        );
      });
    }
    const footer = root.createDiv({
      cls: "custom-syntax-panel-footer custom-syntax-panel-footer--main"
    });
    const langBtn = footer.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": t.languageSwitch }
    });
    (0, import_obsidian2.setIcon)(langBtn, "languages");
    langBtn.addEventListener("click", () => {
      new LanguageModal(this.app, this.plugin).open();
    });
    const settingsBtn = footer.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": t.openSettings }
    });
    (0, import_obsidian2.setIcon)(settingsBtn, "settings");
    settingsBtn.addEventListener("click", () => {
      void this.plugin.openPluginSettings();
    });
  }
  renderEditor(root, t) {
    const nav = root.createDiv({
      cls: "custom-syntax-panel-nav is-editor"
    });
    const back = nav.createEl("button", {
      cls: "clickable-icon",
      attr: { "aria-label": t.back }
    });
    (0, import_obsidian2.setIcon)(back, "chevron-left");
    back.addEventListener("click", () => this.closeEditor());
    nav.createDiv({
      cls: "custom-syntax-panel-nav-title",
      text: this.editing ? t.editTitle : t.createTitle
    });
    const body = root.createDiv({ cls: "custom-syntax-panel-body" });
    this.form = new RuleForm(
      body,
      this.plugin,
      this.editing,
      () => this.submit()
    );
    const footer = root.createDiv({ cls: "custom-syntax-panel-footer" });
    const visBtn = footer.createEl("button", {
      text: t.visualEdit,
      cls: "custom-syntax-visual-edit"
    });
    visBtn.disabled = true;
    visBtn.title = t.visualEditHint;
    const actions = footer.createDiv({
      cls: "custom-syntax-panel-footer-right"
    });
    const cancel = actions.createEl("button", { text: t.cancel });
    cancel.addEventListener("click", () => this.closeEditor());
    const submit = actions.createEl("button", {
      text: this.editing ? t.save : t.create,
      cls: "mod-cta"
    });
    submit.addEventListener("click", () => this.submit());
  }
  openEditor(rule) {
    this.editing = rule;
    this.mode = "editor";
    this.rebuild();
  }
  closeEditor() {
    var _a;
    this.mode = "list";
    this.editing = null;
    (_a = this.form) == null ? void 0 : _a.destroy();
    this.form = null;
    this.rebuild();
  }
  async submit() {
    var _a, _b;
    const res = (_a = this.form) == null ? void 0 : _a.validate();
    if (!res || !res.ok) {
      return;
    }
    const v = res.value;
    if (this.editing) {
      this.editing.name = v.name;
      this.editing.kind = v.kind;
      this.editing.open = v.open;
      this.editing.close = v.close;
      this.editing.readType = v.readType;
      this.editing.captureParams = v.captureParams;
      this.editing.css = v.css;
      this.editing.className = v.className;
      this.editing.enabled = v.enabled;
      this.editing.conflictWithId = null;
    } else {
      this.plugin.settings.rules.push({
        id: newRuleId(),
        name: v.name,
        kind: v.kind,
        open: v.open,
        close: v.close,
        readType: v.readType,
        captureParams: v.captureParams,
        css: v.css,
        className: v.className,
        enabled: v.enabled,
        conflictWithId: null
      });
    }
    this.mode = "list";
    this.editing = null;
    (_b = this.form) == null ? void 0 : _b.destroy();
    this.form = null;
    await this.plugin.saveSettings();
    this.rebuild();
  }
};

// src/main.ts
var CustomSyntaxPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.editorExtension = [];
    this.ribbonEl = null;
    this.settingTab = null;
    /** Own queryable index of where custom rules matched (no metadata-cache patch). */
    this.syntaxIndex = new SyntaxIndex();
    this.indexTimers = /* @__PURE__ */ new Map();
  }
  async onload() {
    await this.loadSettings();
    this.settingTab = new CustomSyntaxSettingTab(this.app, this);
    this.addSettingTab(this.settingTab);
    this.registerView(
      VIEW_TYPE_RULE_PANEL,
      (leaf) => new RulePanelView(leaf, this)
    );
    this.ribbonEl = this.addRibbonIcon(
      "braces",
      stringsFor(this.settings.language).pluginName,
      () => this.activateRulePanel()
    );
    this.updateRibbonVisibility();
    this.editorExtension.push(createEditorExtension(() => this.settings.rules));
    this.registerEditorExtension(this.editorExtension);
    this.registerMarkdownPostProcessor((el) => {
      for (const rule of this.settings.rules) {
        applyRule(el, rule);
      }
    });
    this.registerEvent(
      this.app.vault.on("modify", (f) => this.scheduleIndex(f))
    );
    this.registerEvent(
      this.app.vault.on("create", (f) => this.scheduleIndex(f))
    );
    this.registerEvent(
      this.app.vault.on("delete", (f) => {
        if (f instanceof import_obsidian3.TFile) this.syntaxIndex.removeFile(f.path);
      })
    );
    this.addCommand({
      id: "write-companion",
      name: "Generate syntax metadata companion",
      callback: () => void this.writeCompanion()
    });
  }
  /** Debounced re-index of a single markdown file (no whole-vault scan). */
  scheduleIndex(file) {
    if (!(file instanceof import_obsidian3.TFile) || file.extension !== "md") return;
    const existing = this.indexTimers.get(file.path);
    if (existing) window.clearTimeout(existing);
    this.indexTimers.set(
      file.path,
      window.setTimeout(() => {
        this.indexTimers.delete(file.path);
        void this.app.vault.read(file).then((content) => {
          this.syntaxIndex.indexFile(
            file.path,
            content,
            this.settings.rules
          );
        });
      }, 300)
    );
  }
  /**
   * Write (or update) a Dataview-readable companion file next to the active
   * note. This is an opt-in bridge so other plugins (e.g. Dataview) can read
   * where custom syntax matched — without patching Obsidian's metadata cache.
   */
  async writeCompanion() {
    const file = this.app.workspace.getActiveFile();
    if (!file || file.extension !== "md") {
      new import_obsidian3.Notice("Open a Markdown note first.");
      return;
    }
    const content = await this.app.vault.read(file);
    const occ = scanContent(content, this.settings.rules);
    const metaName = `${file.basename}.cs-meta.md`;
    const metaPath = file.parent ? `${file.parent.path}/${metaName}` : metaName;
    const body = buildCompanion(file.basename, occ);
    const existing = this.app.vault.getAbstractFileByPath(metaPath);
    if (existing instanceof import_obsidian3.TFile) {
      await this.app.vault.modify(existing, body);
    } else {
      await this.app.vault.create(metaPath, body);
    }
    new import_obsidian3.Notice(`Wrote ${metaName}`);
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_RULE_PANEL);
  }
  async loadSettings() {
    var _a;
    const data = await this.loadData();
    this.settings = {
      language: "system",
      rules: [],
      showRibbon: true
    };
    const lang = data == null ? void 0 : data.language;
    this.settings.language = lang === "en" || lang === "zh" || lang === "system" ? lang : "system";
    const rules = data == null ? void 0 : data.rules;
    if (Array.isArray(rules)) {
      this.settings.rules = rules.map((r) => normalizeRule(r));
    } else {
      this.settings.rules = DEFAULT_SETTINGS.rules.map((r) => ({ ...r }));
    }
    this.settings.showRibbon = (_a = data == null ? void 0 : data.showRibbon) != null ? _a : true;
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refresh();
  }
  refresh() {
    var _a;
    this.editorExtension.length = 0;
    this.editorExtension.push(createEditorExtension(() => this.settings.rules));
    this.app.workspace.updateOptions();
    this.rerenderPreviews();
    this.notifyRulePanel();
    const appSetting = this.app.setting;
    if ((appSetting == null ? void 0 : appSetting.activeTab) === this.settingTab) {
      (_a = this.settingTab) == null ? void 0 : _a.display();
    }
    this.updateRibbon();
  }
  /** Open this plugin's page in Obsidian's native settings. */
  async openPluginSettings() {
    const appSetting = this.app.setting;
    if (!appSetting) return;
    appSetting.open();
    await new Promise((r) => setTimeout(r, 0));
    appSetting.openTabById(this.manifest.id);
  }
  /** Keep the ribbon icon's tooltip in sync with the active language. */
  updateRibbon() {
    if (this.ribbonEl) {
      const name = stringsFor(this.settings.language).pluginName;
      this.ribbonEl.setAttribute("aria-label", name);
      this.ribbonEl.title = name;
    }
  }
  /**
   * `updateOptions()` only refreshes editors. Reading view content is
   * produced once by the post-processor, so it has to be re-rendered
   * explicitly for a rule change to show up there.
   */
  rerenderPreviews() {
    this.app.workspace.iterateAllLeaves((leaf) => {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView && view.previewMode) {
        view.previewMode.rerender(true);
      }
    });
  }
  /** Rebuild the rule-manager panel if it is currently open. */
  notifyRulePanel() {
    this.app.workspace.getLeavesOfType(VIEW_TYPE_RULE_PANEL).forEach((leaf) => {
      if (leaf.view instanceof RulePanelView) {
        leaf.view.rebuild();
      }
    });
  }
  /** Open (or reveal) the rule-manager panel in the right sidebar. */
  activateRulePanel() {
    const { workspace } = this.app;
    const existing = workspace.getLeavesOfType(VIEW_TYPE_RULE_PANEL);
    let leaf = existing[0];
    if (!leaf) {
      const right = workspace.getRightLeaf(false);
      if (right) {
        leaf = right;
        leaf.setViewState({
          type: VIEW_TYPE_RULE_PANEL,
          active: true
        });
      }
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  /** Show or hide the left-ribbon icon based on `settings.showRibbon`. */
  updateRibbonVisibility() {
    if (this.ribbonEl) {
      this.ribbonEl.toggleClass(
        "custom-syntax-ribbon-hidden",
        !this.settings.showRibbon
      );
    }
  }
};
