/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the plugin source repository
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => CustomSyntaxPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/editorExtension.ts
var import_language = require("@codemirror/language");
var import_view = require("@codemirror/view");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  language: "system",
  rules: [
    {
      id: "rounded-box",
      name: "\u5706\u89D2\u8FB9\u6846",
      delimiter: "++",
      css: "border: 1px solid var(--interactive-accent); border-radius: 6px; padding: 1px 5px;",
      enabled: true
    }
  ]
};
function newRuleId() {
  return `r${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}
function normalizeRule(r) {
  var _a, _b, _c, _d;
  return {
    id: typeof r.id === "string" && r.id ? r.id : newRuleId(),
    name: typeof r.name === "string" ? r.name : "",
    delimiter: (_a = r.delimiter) != null ? _a : "",
    css: (_b = r.css) != null ? _b : "",
    enabled: (_c = r.enabled) != null ? _c : true,
    conflictWithId: (_d = r.conflictWithId) != null ? _d : null
  };
}
function ruleClassName(id) {
  return `custom-syntax-${id}`;
}
function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
function delimitersConflict(a, b) {
  if (!a || !b) {
    return false;
  }
  return a === b || a.includes(b) || b.includes(a);
}
var BUILTIN = [
  { delim: "**", zh: "\u7C97\u4F53", en: "Bold" },
  { delim: "__", zh: "\u7C97\u4F53", en: "Bold" },
  { delim: "*", zh: "\u659C\u4F53", en: "Italic" },
  { delim: "_", zh: "\u659C\u4F53", en: "Italic" },
  { delim: "~~", zh: "\u5220\u9664\u7EBF", en: "Strikethrough" },
  { delim: "==", zh: "\u9AD8\u4EAE", en: "Highlight" },
  { delim: "`", zh: "\u884C\u5185\u4EE3\u7801", en: "Inline code" },
  { delim: "```", zh: "\u4EE3\u7801\u5757", en: "Code block" },
  { delim: "%%", zh: "\u6CE8\u91CA", en: "Comment" },
  { delim: "$", zh: "\u6570\u5B66\u516C\u5F0F", en: "Math" },
  { delim: "#", zh: "\u6807\u9898", en: "Heading" },
  { delim: ">", zh: "\u5F15\u7528", en: "Blockquote" },
  { delim: "|", zh: "\u8868\u683C", en: "Table" },
  { delim: "[[", zh: "\u5185\u90E8\u94FE\u63A5", en: "Wikilink" },
  { delim: "![[", zh: "\u5D4C\u5165", en: "Embed" },
  { delim: "[", zh: "\u94FE\u63A5", en: "Link" },
  { delim: "]", zh: "\u94FE\u63A5", en: "Link" },
  { delim: "(", zh: "\u94FE\u63A5", en: "Link" },
  { delim: ")", zh: "\u94FE\u63A5", en: "Link" },
  { delim: "!", zh: "\u56FE\u7247", en: "Image" },
  { delim: "^", zh: "\u4E0A\u6807/\u811A\u6CE8", en: "Superscript/Footnote" },
  { delim: "~", zh: "\u4E0B\u6807", en: "Subscript" }
];
function findBuiltinConflict(delim) {
  for (const b of BUILTIN) {
    if (delimitersConflict(delim, b.delim)) {
      return b;
    }
  }
  return null;
}
function findCustomConflict(delim, rules, excludeId) {
  for (const r of rules) {
    if (excludeId && r.id === excludeId) {
      continue;
    }
    if (delimitersConflict(delim, r.delimiter)) {
      return r;
    }
  }
  return null;
}
var STRINGS = {
  zh: {
    pluginName: "\u81EA\u5B9A\u4E49\u8BED\u6CD5",
    addRule: "\u6DFB\u52A0\u89C4\u5219",
    followSystem: "\u8DDF\u968F\u7CFB\u7EDF",
    toggle: "\u542F\u7528\u6216\u7981\u7528",
    edit: "\u7F16\u8F91",
    delete: "\u5220\u9664",
    deleteConfirm: "\u786E\u5B9A\u8981\u5220\u9664\u89C4\u5219\u300C{name}\u300D\u5417\uFF1F",
    createTitle: "\u65B0\u5EFA\u89C4\u5219",
    editTitle: "\u7F16\u8F91\u89C4\u5219",
    ruleName: "\u89C4\u5219\u540D",
    ruleNamePlaceholder: "\u7ED9\u89C4\u5219\u8D77\u4E2A\u540D\u5B57",
    delimiter: "\u5206\u9694\u7B26",
    delimiterDesc: "\u5305\u88F9\u6587\u5B57\u7684\u6807\u8BB0\uFF0C\u4F8B\u5982 ++",
    css: "CSS \u6837\u5F0F",
    cssDesc: "\u5E94\u7528\u5230\u5339\u914D\u6587\u5B57\u7684\u539F\u59CB CSS \u58F0\u660E\uFF0C\u4F8B\u5982 border: 1px solid red;",
    cssPlaceholder: "border: 1px solid var(--interactive-accent); border-radius: 6px;",
    cancel: "\u53D6\u6D88",
    create: "\u521B\u5EFA",
    save: "\u4FDD\u5B58",
    delimiterRequired: "\u5206\u9694\u7B26\u4E0D\u80FD\u4E3A\u7A7A",
    conflictBuiltin: "\u4E0E Markdown \u5185\u7F6E\u8BED\u6CD5\u300C{name}\u300D\u51B2\u7A81",
    conflictCustomCreate: "\u4E0E\u81EA\u5B9A\u4E49\u8BED\u6CD5\u300C{name}\u300D\u51B2\u7A81\uFF0C\u518D\u6B21\u786E\u8BA4\u5C06\u521B\u5EFA\u5E76\u7981\u7528",
    conflictCustomSave: "\u4E0E\u81EA\u5B9A\u4E49\u8BED\u6CD5\u300C{name}\u300D\u51B2\u7A81\uFF0C\u518D\u6B21\u786E\u8BA4\u5C06\u4FDD\u5B58\u5E76\u7981\u7528",
    conflictAnnotation: "\u4E0E\u300C{name}\u300D\u51B2\u7A81",
    untitled: "\u672A\u547D\u540D"
  },
  en: {
    pluginName: "Custom Syntax",
    addRule: "Add rule",
    followSystem: "Follow system",
    toggle: "Enable or disable",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: 'Delete rule "{name}"?',
    createTitle: "New rule",
    editTitle: "Edit rule",
    ruleName: "Rule name",
    ruleNamePlaceholder: "Name this rule",
    delimiter: "Delimiter",
    delimiterDesc: "The marker that wraps the text, e.g. ++",
    css: "CSS",
    cssDesc: "Raw CSS declarations applied to the matched text, e.g. border: 1px solid red;",
    cssPlaceholder: "border: 1px solid var(--interactive-accent); border-radius: 6px;",
    cancel: "Cancel",
    create: "Create",
    save: "Save",
    delimiterRequired: "Delimiter is required",
    conflictBuiltin: 'Conflicts with built-in Markdown syntax "{name}"',
    conflictCustomCreate: 'Conflicts with custom syntax "{name}" \u2014 confirm again to create (disabled)',
    conflictCustomSave: 'Conflicts with custom syntax "{name}" \u2014 confirm again to save (disabled)',
    conflictAnnotation: 'Conflicts with "{name}"',
    untitled: "Untitled"
  }
};
function resolveLanguage(lang) {
  if (lang === "system") {
    const nav = typeof navigator !== "undefined" ? navigator.language || "" : "";
    return nav.toLowerCase().startsWith("zh") ? "zh" : "en";
  }
  return lang;
}
function getStrings(lang) {
  var _a;
  return (_a = STRINGS[lang]) != null ? _a : STRINGS.zh;
}
function stringsFor(lang) {
  return getStrings(resolveLanguage(lang));
}
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, message, confirmLabel, cancelLabel, onConfirm) {
    super(app);
    this.message = message;
    this.confirmLabel = confirmLabel;
    this.cancelLabel = cancelLabel;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("p", {
      cls: "custom-syntax-confirm-message",
      text: this.message
    });
    const btnRow = contentEl.createDiv({ cls: "custom-syntax-modal-actions" });
    const cancelBtn = btnRow.createEl("button", { text: this.cancelLabel });
    cancelBtn.addEventListener("click", () => this.close());
    const confirmBtn = btnRow.createEl("button", {
      text: this.confirmLabel,
      cls: "mod-warning"
    });
    confirmBtn.addEventListener("click", () => {
      this.close();
      this.onConfirm();
    });
  }
};
var RuleModal = class extends import_obsidian.Modal {
  constructor(app, plugin, rule, onDone) {
    super(app);
    this.pendingCustomConflict = null;
    this.plugin = plugin;
    this.rule = rule;
    this.onDone = onDone;
  }
  onOpen() {
    const t = stringsFor(this.plugin.settings.language);
    this.titleEl.setText(this.rule ? t.editTitle : t.createTitle);
    const { contentEl } = this;
    new import_obsidian.Setting(contentEl).setName(t.ruleName).addText((text) => {
      var _a, _b;
      this.nameInput = text.inputEl;
      text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.name) != null ? _b : "").setPlaceholder(t.ruleNamePlaceholder);
    });
    new import_obsidian.Setting(contentEl).setName(t.delimiter).setDesc(t.delimiterDesc).addText((text) => {
      var _a, _b;
      this.delimInput = text.inputEl;
      text.setValue((_b = (_a = this.rule) == null ? void 0 : _a.delimiter) != null ? _b : "++").setPlaceholder("++");
      this.delimInput.addEventListener("input", () => {
        this.pendingCustomConflict = null;
        this.clearError();
      });
    });
    new import_obsidian.Setting(contentEl).setName(t.css).setDesc(t.cssDesc).addTextArea((ta) => {
      var _a, _b;
      this.cssInput = ta.inputEl;
      ta.setValue(
        (_b = (_a = this.rule) == null ? void 0 : _a.css) != null ? _b : DEFAULT_SETTINGS.rules[0].css
      ).setPlaceholder(t.cssPlaceholder);
      this.cssInput.rows = 3;
      this.cssInput.addClass("custom-syntax-css-input");
    });
    this.errorEl = contentEl.createDiv({ cls: "custom-syntax-error" });
    const btnRow = contentEl.createDiv({ cls: "custom-syntax-modal-actions" });
    const cancelBtn = btnRow.createEl("button", { text: t.cancel });
    cancelBtn.addEventListener("click", () => this.close());
    const submitBtn = btnRow.createEl("button", {
      text: this.rule ? t.save : t.create,
      cls: "mod-cta"
    });
    submitBtn.addEventListener("click", () => this.onSubmit());
  }
  clearError() {
    this.errorEl.empty();
    this.errorEl.removeClass("is-visible");
  }
  showError(msg) {
    this.errorEl.empty();
    this.errorEl.createSpan({ text: msg });
    this.errorEl.addClass("is-visible");
  }
  onSubmit() {
    var _a;
    const t = stringsFor(this.plugin.settings.language);
    const lang = resolveLanguage(this.plugin.settings.language);
    const name = this.nameInput.value.trim();
    const delimiter = this.delimInput.value;
    const css = this.cssInput.value;
    if (!delimiter) {
      this.showError(t.delimiterRequired);
      return;
    }
    const builtin = findBuiltinConflict(delimiter);
    if (builtin) {
      const nm = lang === "zh" ? builtin.zh : builtin.en;
      this.showError(t.conflictBuiltin.replace("{name}", nm));
      this.pendingCustomConflict = null;
      return;
    }
    const custom = findCustomConflict(
      delimiter,
      this.plugin.settings.rules,
      (_a = this.rule) == null ? void 0 : _a.id
    );
    if (custom) {
      const nm = custom.name || t.untitled;
      if (this.pendingCustomConflict && this.pendingCustomConflict.id === custom.id) {
        this.finish(name, delimiter, css, false);
        return;
      }
      this.pendingCustomConflict = custom;
      const msg = this.rule ? t.conflictCustomSave : t.conflictCustomCreate;
      this.showError(msg.replace("{name}", nm));
      return;
    }
    this.finish(name, delimiter, css, this.rule ? this.rule.enabled : true);
  }
  finish(name, delimiter, css, enabled) {
    const t = stringsFor(this.plugin.settings.language);
    const finalName = name || t.untitled;
    if (this.rule) {
      this.rule.name = finalName;
      this.rule.delimiter = delimiter;
      this.rule.css = css;
      this.rule.enabled = enabled;
      this.rule.conflictWithId = null;
    } else {
      this.plugin.settings.rules.push({
        id: newRuleId(),
        name: finalName,
        delimiter,
        css,
        enabled,
        conflictWithId: null
      });
    }
    void this.plugin.saveSettings();
    this.close();
    this.onDone();
  }
};
var CustomSyntaxSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const t = stringsFor(this.plugin.settings.language);
    const nav = containerEl.createDiv({ cls: "custom-syntax-nav" });
    const title = nav.createDiv({ cls: "custom-syntax-nav-title" });
    title.createSpan({ text: t.pluginName });
    title.createSpan({
      cls: "custom-syntax-nav-version",
      text: `v${this.plugin.manifest.version}`
    });
    const actions = nav.createDiv({ cls: "custom-syntax-nav-actions" });
    const langSelect = actions.createEl("select");
    langSelect.addClass("dropdown");
    const options = [
      ["system", t.followSystem],
      ["zh", "\u4E2D\u6587"],
      ["en", "English"]
    ];
    for (const [value, label] of options) {
      const opt = langSelect.createEl("option");
      opt.value = value;
      opt.textContent = label;
    }
    langSelect.value = this.plugin.settings.language;
    langSelect.addEventListener("change", () => {
      this.plugin.settings.language = langSelect.value;
      void this.plugin.saveSettings();
      this.display();
    });
    const addBtn = actions.createEl("button", {
      text: t.addRule,
      cls: "mod-cta"
    });
    addBtn.addEventListener("click", () => {
      new RuleModal(this.app, this.plugin, null, () => this.display()).open();
    });
    const list = containerEl.createDiv({ cls: "custom-syntax-rules" });
    this.plugin.settings.rules.forEach((rule) => {
      this.renderRuleCard(list, rule);
    });
  }
  renderRuleCard(containerEl, rule) {
    const t = stringsFor(this.plugin.settings.language);
    const card = containerEl.createDiv({ cls: "custom-syntax-rule-card" });
    const row = card.createDiv({ cls: "custom-syntax-rule-row" });
    const nameEl = row.createDiv({
      cls: "custom-syntax-rule-name",
      text: rule.name || t.untitled
    });
    nameEl.title = rule.delimiter;
    const controls = row.createDiv({ cls: "custom-syntax-rule-controls" });
    const toggle = controls.createDiv({
      cls: rule.enabled ? "checkbox-container is-enabled" : "checkbox-container"
    });
    toggle.setAttribute("role", "switch");
    toggle.setAttribute("aria-checked", String(rule.enabled));
    toggle.setAttribute("aria-label", t.toggle);
    toggle.setAttribute("tabindex", "0");
    toggle.addEventListener("click", () => {
      const newVal = !rule.enabled;
      toggle.toggleClass("is-enabled", newVal);
      toggle.setAttribute("aria-checked", String(newVal));
      void this.toggleRule(rule, newVal);
      window.setTimeout(() => this.display(), 180);
    });
    toggle.addEventListener("keydown", (ev) => {
      if (ev.key === " " || ev.key === "Enter") {
        ev.preventDefault();
        toggle.click();
      }
    });
    const editBtn = controls.createEl("button", { cls: "clickable-icon" });
    editBtn.setAttribute("aria-label", t.edit);
    (0, import_obsidian.setIcon)(editBtn, "pencil");
    editBtn.addEventListener("click", () => {
      new RuleModal(this.app, this.plugin, rule, () => this.display()).open();
    });
    const delBtn = controls.createEl("button", { cls: "clickable-icon" });
    delBtn.setAttribute("aria-label", t.delete);
    (0, import_obsidian.setIcon)(delBtn, "trash");
    delBtn.addEventListener("click", () => {
      const name = rule.name || t.untitled;
      new ConfirmModal(
        this.app,
        t.deleteConfirm.replace("{name}", name),
        t.delete,
        t.cancel,
        () => {
          void this.deleteRule(rule);
        }
      ).open();
    });
    if (rule.conflictWithId) {
      const other = this.plugin.settings.rules.find(
        (r) => r.id === rule.conflictWithId
      );
      if (other) {
        card.createDiv({
          cls: "custom-syntax-rule-conflict",
          text: t.conflictAnnotation.replace(
            "{name}",
            other.name || t.untitled
          )
        });
      }
    }
  }
  async toggleRule(rule, enabled) {
    rule.enabled = enabled;
    rule.conflictWithId = null;
    if (enabled) {
      for (const other of this.plugin.settings.rules) {
        if (other !== rule && other.enabled && delimitersConflict(rule.delimiter, other.delimiter)) {
          other.enabled = false;
          other.conflictWithId = rule.id;
        }
      }
    }
    await this.plugin.saveSettings();
  }
  async deleteRule(rule) {
    this.plugin.settings.rules = this.plugin.settings.rules.filter(
      (r) => r !== rule
    );
    for (const r of this.plugin.settings.rules) {
      if (r.conflictWithId === rule.id) {
        r.conflictWithId = null;
      }
    }
    await this.plugin.saveSettings();
    this.display();
  }
};

// src/editorExtension.ts
function collectCodeRanges(view) {
  const ranges = [];
  try {
    for (const { from, to } of view.visibleRanges) {
      (0, import_language.syntaxTree)(view.state).iterate({
        from,
        to,
        enter(node) {
          const name = node.name.toLowerCase();
          if (name.includes("code") || name.includes("comment") || name.includes("math") || name.includes("html")) {
            ranges.push({ from: node.from, to: node.to });
            return false;
          }
        }
      });
    }
  } catch (e) {
    return [];
  }
  return ranges;
}
function isInCode(from, to, ranges) {
  for (const r of ranges) {
    if (from < r.to && to > r.from) {
      return true;
    }
  }
  return false;
}
function buildDecorations(view, rules) {
  const decos = [];
  const codeRanges = collectCodeRanges(view);
  const scanRanges = view.visibleRanges.length > 0 ? view.visibleRanges : [{ from: 0, to: view.state.doc.length }];
  const sel = view.state.selection.main;
  for (const rule of rules) {
    if (!rule.enabled || !rule.delimiter || !rule.css) {
      continue;
    }
    const delim = rule.delimiter;
    const re = new RegExp(
      `${escapeRegExp(delim)}([^\\n]*?)${escapeRegExp(delim)}`,
      "g"
    );
    const delimCls = ruleClassName(rule.id) + "-delim";
    for (const { from, to } of scanRanges) {
      const text = view.state.sliceDoc(from, to);
      re.lastIndex = 0;
      let m;
      while ((m = re.exec(text)) !== null) {
        const content = m[1];
        const fullStart = from + m.index;
        const contentStart = fullStart + delim.length;
        const contentEnd = contentStart + content.length;
        const fullEnd = fullStart + m[0].length;
        if (isInCode(fullStart, fullEnd, codeRanges)) {
          continue;
        }
        const active = sel.from <= fullEnd && sel.to >= fullStart;
        if (active) {
          decos.push(
            import_view.Decoration.mark({
              class: delimCls
            }).range(fullStart, contentStart)
          );
        } else {
          decos.push(
            import_view.Decoration.replace({}).range(fullStart, contentStart)
          );
        }
        decos.push(
          import_view.Decoration.mark({
            attributes: { style: rule.css }
          }).range(contentStart, contentEnd)
        );
        if (active) {
          decos.push(
            import_view.Decoration.mark({
              class: delimCls
            }).range(contentEnd, fullEnd)
          );
        } else {
          decos.push(
            import_view.Decoration.replace({}).range(contentEnd, fullEnd)
          );
        }
      }
    }
  }
  return import_view.Decoration.set(decos, true);
}
function createEditorExtension(getRules) {
  class CustomSyntaxView {
    constructor(view) {
      this.decorations = buildDecorations(view, getRules());
    }
    update(update) {
      if (update.docChanged || update.viewportChanged || update.selectionSet) {
        this.decorations = buildDecorations(update.view, getRules());
      }
    }
    destroy() {
    }
  }
  const spec = {
    decorations: (value) => value.decorations
  };
  return import_view.ViewPlugin.fromClass(CustomSyntaxView, spec);
}

// src/postProcessor.ts
function shouldSkip(node) {
  let el = node.parentElement;
  while (el) {
    const tag = el.tagName;
    if (tag === "CODE" || tag === "PRE" || tag === "A" || tag === "MATH" || tag === "SCRIPT" || tag === "STYLE") {
      return true;
    }
    el = el.parentElement;
  }
  return false;
}
function cssToRecord(css) {
  const result = {};
  for (const decl of css.split(";")) {
    const trimmed = decl.trim();
    if (!trimmed) continue;
    const idx = trimmed.indexOf(":");
    if (idx === -1) continue;
    const prop = trimmed.slice(0, idx).trim();
    const value = trimmed.slice(idx + 1).trim();
    if (prop && value) {
      result[prop] = value;
    }
  }
  return result;
}
function applyRule(root, rule) {
  var _a, _b, _c;
  if (!rule.enabled || !rule.delimiter || !rule.css) {
    return;
  }
  const delim = rule.delimiter;
  const re = new RegExp(
    `${escapeRegExp(delim)}([^\\n]*?)${escapeRegExp(delim)}`,
    "g"
  );
  const cssRecord = cssToRecord(rule.css);
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const textNodes = [];
  while (walker.nextNode()) {
    const node = walker.currentNode;
    if (shouldSkip(node)) {
      continue;
    }
    if (((_a = node.nodeValue) != null ? _a : "").length === 0) {
      continue;
    }
    textNodes.push(node);
  }
  for (const node of textNodes) {
    const text = (_b = node.nodeValue) != null ? _b : "";
    if (!re.test(text)) {
      re.lastIndex = 0;
      continue;
    }
    re.lastIndex = 0;
    const fragment = createFragment();
    let lastIndex = 0;
    let m;
    while ((m = re.exec(text)) !== null) {
      if (m.index > lastIndex) {
        fragment.appendChild(document.createTextNode(text.slice(lastIndex, m.index)));
      }
      const span = createSpan();
      span.setCssStyles(cssRecord);
      span.textContent = m[1];
      fragment.appendChild(span);
      lastIndex = m.index + m[0].length;
      if (m[0].length === 0) {
        re.lastIndex++;
      }
    }
    if (lastIndex < text.length) {
      fragment.appendChild(document.createTextNode(text.slice(lastIndex)));
    }
    (_c = node.parentNode) == null ? void 0 : _c.replaceChild(fragment, node);
  }
}

// src/main.ts
var CustomSyntaxPlugin = class extends import_obsidian2.Plugin {
  constructor() {
    super(...arguments);
    this.editorExtension = [];
  }
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new CustomSyntaxSettingTab(this.app, this));
    this.editorExtension.push(createEditorExtension(() => this.settings.rules));
    this.registerEditorExtension(this.editorExtension);
    this.registerMarkdownPostProcessor((el) => {
      for (const rule of this.settings.rules) {
        applyRule(el, rule);
      }
    });
  }
  onunload() {
  }
  async loadSettings() {
    const data = await this.loadData();
    this.settings = { language: "system", rules: [] };
    const lang = data == null ? void 0 : data.language;
    this.settings.language = lang === "en" || lang === "zh" || lang === "system" ? lang : "system";
    const rules = data == null ? void 0 : data.rules;
    if (Array.isArray(rules)) {
      this.settings.rules = rules.map((r) => normalizeRule(r));
    } else {
      this.settings.rules = DEFAULT_SETTINGS.rules.map((r) => ({ ...r }));
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
    this.refresh();
  }
  refresh() {
    this.editorExtension.length = 0;
    this.editorExtension.push(createEditorExtension(() => this.settings.rules));
    this.app.workspace.updateOptions();
  }
};
