import { App, Modal, PluginSettingTab, Setting, setIcon } from "obsidian";
import type CustomSyntaxPlugin from "./main";
import { createCssEditor, type CssEditorHandle } from "./cssEditor";

export type Language = "en" | "zh" | "system";
type ResolvedLanguage = "en" | "zh";

export interface SyntaxRule {
	id: string;
	name: string;
	delimiter: string;
	/**
	 * Declarations only — the text that goes *inside* a rule's curly braces.
	 * May be left empty, in which case the rule's classes (see `className`)
	 * alone decide the look, and styling lives in the user's own CSS snippet.
	 */
	css: string;
	/**
	 * Optional extra class names applied to every match, so styles can be
	 * shared between rules and overridden from a CSS snippet or theme.
	 */
	className: string;
	enabled: boolean;
	conflictWithId?: string | null;
}

export interface CustomSyntaxSettings {
	language: Language;
	rules: SyntaxRule[];
}

export const DEFAULT_SETTINGS: CustomSyntaxSettings = {
	language: "system",
	rules: [
		{
			id: "rounded-box",
			name: "圆角边框",
		delimiter: "++",
		css: `border: 1px solid var(--interactive-accent);
border-radius: 6px;
padding: 1px 5px;`,
		className: "",
		enabled: true,
		},
	],
};

export function newRuleId(): string {
	return `r${Date.now().toString(36)}${Math.random().toString(36).slice(2, 6)}`;
}

export function normalizeRule(r: Partial<SyntaxRule>): SyntaxRule {
	return {
		id: typeof r.id === "string" && r.id ? r.id : newRuleId(),
		name: typeof r.name === "string" ? r.name : "",
		delimiter: r.delimiter ?? "",
		css: r.css ?? "",
		className: sanitizeClassName(r.className ?? ""),
		enabled: r.enabled ?? true,
		conflictWithId: r.conflictWithId ?? null,
	};
}

export function ruleClassName(id: string): string {
	return `custom-syntax-${id}`;
}

/**
 * Keeps only tokens that are valid, safe CSS identifiers, so a malformed or
 * malicious value can never break out of the class attribute.
 */
export function sanitizeClassName(raw: string): string {
	return (raw ?? "")
		.split(/\s+/)
		.map((token) => token.trim())
		.filter((token) => /^-?[A-Za-z_][A-Za-z0-9_-]*$/.test(token))
		.join(" ");
}

/** Stable per-rule class, so a CSS snippet can target one rule exactly. */
export function ruleContentClass(id: string): string {
	return `${ruleClassName(id)}-content`;
}

/**
 * The full class list applied to matched text: a shared base class, the
 * rule's own stable class, then any user-supplied extra classes.
 */
export function contentClasses(rule: SyntaxRule): string {
	const parts = ["custom-syntax-content", ruleContentClass(rule.id)];
	const extra = sanitizeClassName(rule.className);
	if (extra) {
		parts.push(extra);
	}
	return parts.join(" ");
}

/**
 * Renders every rule's declarations as a plain CSS snippet the user can paste
 * into their own snippet file, after which the rule's `css` field can be
 * cleared so the snippet (and themes) fully control the look.
 */
export function exportRulesAsCss(rules: SyntaxRule[]): string {
	const blocks: string[] = [];
	for (const rule of rules) {
		const css = (rule.css ?? "").trim();
		if (!css) {
			continue;
		}
		const extra = sanitizeClassName(rule.className);
		const selector = extra
			? `.${extra.split(" ").join(".")}`
			: `.${ruleContentClass(rule.id)}`;
		const label = rule.name || rule.delimiter || rule.id;
		const declarations = css
			.split(";")
			.map((decl) => decl.trim())
			.filter(Boolean)
			.map((decl) => `\t${decl};`)
			.join("\n");
		blocks.push(
			`/* ${label} — ${rule.delimiter} */\n${selector} {\n${declarations}\n}`
		);
	}
	if (blocks.length === 0) {
		return "";
	}
	return [
		"/* Generated by the Custom Syntax plugin. */",
		"/* Paste into a CSS snippet, then clear the rule's declarations so the snippet takes over. */",
		"",
		...blocks,
	].join("\n");
}

export function escapeRegExp(s: string): string {
	return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

export function delimitersConflict(a: string, b: string): boolean {
	if (!a || !b) {
		return false;
	}
	return a === b || a.includes(b) || b.includes(a);
}

interface BuiltinSyntax {
	delim: string;
	zh: string;
	en: string;
}

const BUILTIN: BuiltinSyntax[] = [
	{ delim: "**", zh: "粗体", en: "Bold" },
	{ delim: "__", zh: "粗体", en: "Bold" },
	{ delim: "*", zh: "斜体", en: "Italic" },
	{ delim: "_", zh: "斜体", en: "Italic" },
	{ delim: "~~", zh: "删除线", en: "Strikethrough" },
	{ delim: "==", zh: "高亮", en: "Highlight" },
	{ delim: "`", zh: "行内代码", en: "Inline code" },
	{ delim: "```", zh: "代码块", en: "Code block" },
	{ delim: "%%", zh: "注释", en: "Comment" },
	{ delim: "$", zh: "数学公式", en: "Math" },
	{ delim: "#", zh: "标题", en: "Heading" },
	{ delim: ">", zh: "引用", en: "Blockquote" },
	{ delim: "|", zh: "表格", en: "Table" },
	{ delim: "[[", zh: "内部链接", en: "Wikilink" },
	{ delim: "![[", zh: "嵌入", en: "Embed" },
	{ delim: "[", zh: "链接", en: "Link" },
	{ delim: "]", zh: "链接", en: "Link" },
	{ delim: "(", zh: "链接", en: "Link" },
	{ delim: ")", zh: "链接", en: "Link" },
	{ delim: "!", zh: "图片", en: "Image" },
	{ delim: "^", zh: "上标/脚注", en: "Superscript/Footnote" },
	{ delim: "~", zh: "下标", en: "Subscript" },
];

export function findBuiltinConflict(delim: string): BuiltinSyntax | null {
	for (const b of BUILTIN) {
		if (delimitersConflict(delim, b.delim)) {
			return b;
		}
	}
	return null;
}

export function findCustomConflict(
	delim: string,
	rules: SyntaxRule[],
	excludeId?: string
): SyntaxRule | null {
	for (const r of rules) {
		if (excludeId && r.id === excludeId) {
			continue;
		}
		if (delimitersConflict(delim, r.delimiter)) {
			return r;
		}
	}
	return null;
}

interface UIStrings {
	pluginName: string;
	addRule: string;
	followSystem: string;
	toggle: string;
	edit: string;
	delete: string;
	deleteConfirm: string;
	createTitle: string;
	editTitle: string;
	ruleName: string;
	ruleNamePlaceholder: string;
	delimiter: string;
	delimiterDesc: string;
	css: string;
	cssDesc: string;
	cssPlaceholder: string;
	cssAria: string;
	visualEdit: string;
	visualEditHint: string;
	className: string;
	classNameDesc: string;
	classNamePlaceholder: string;
	exportName: string;
	exportDesc: string;
	exportBtn: string;
	exportTitle: string;
	exportEmpty: string;
	copy: string;
	copied: string;
	copyFailed: string;
	cancel: string;
	create: string;
	save: string;
	delimiterRequired: string;
	conflictBuiltin: string;
	conflictCustomCreate: string;
	conflictCustomSave: string;
	conflictAnnotation: string;
	untitled: string;
}

const STRINGS: Record<ResolvedLanguage, UIStrings> = {
	zh: {
		pluginName: "自定义语法",
		addRule: "添加规则",
		followSystem: "跟随系统",
		toggle: "启用或禁用",
		edit: "编辑",
		delete: "删除",
		deleteConfirm: "确定要删除规则「{name}」吗？",
		createTitle: "新建规则",
		editTitle: "编辑规则",
		ruleName: "规则名",
		ruleNamePlaceholder: "给规则起个名字",
		delimiter: "分隔符",
		delimiterDesc: "包裹文字的标记，例如 ++",
		css: "样式声明",
		cssDesc:
			"只写 CSS 花括号 { } 里的内容，例如 color: red;。留空则完全由下方类名在你自己的 CSS 片段中决定样式。",
		cssPlaceholder: `border: 1px solid var(--interactive-accent);
border-radius: 6px;
padding: 1px 5px;`,
		cssAria: "CSS 样式声明",
		visualEdit: "可视化编辑",
		visualEditHint: "即将推出：用图形界面调整样式，无需手写 CSS",
		className: "类名（可选）",
		classNameDesc:
			"附加到匹配文字上的 CSS 类名，多个用空格分隔。样式声明留空时，样式完全由你在 CSS 片段中为这个类写的规则决定。",
		classNamePlaceholder: "my-highlight",
		exportName: "导出为 CSS 片段",
		exportDesc:
			"把规则的样式声明导出成 CSS 片段。粘到你的 CSS 片段文件并启用后，清空规则的样式声明即可改由片段控制，样式也就能被主题复用和覆盖。",
		exportBtn: "导出",
		exportTitle: "导出 CSS 片段",
		exportEmpty: "还没有规则填写样式声明，没有可导出的内容。",
		copy: "复制到剪贴板",
		copied: "已复制",
		copyFailed: "复制失败，请手动选中复制",
		cancel: "取消",
		create: "创建",
		save: "保存",
		delimiterRequired: "分隔符不能为空",
		conflictBuiltin: "与 Markdown 内置语法「{name}」冲突",
		conflictCustomCreate: "与自定义语法「{name}」冲突，再次确认将创建并禁用",
		conflictCustomSave: "与自定义语法「{name}」冲突，再次确认将保存并禁用",
		conflictAnnotation: "与「{name}」冲突",
		untitled: "未命名",
	},
	en: {
		pluginName: "Custom Syntax",
		addRule: "Add rule",
		followSystem: "Follow system",
		toggle: "Enable or disable",
		edit: "Edit",
		delete: "Delete",
		deleteConfirm: "Delete rule \"{name}\"?",
		createTitle: "New rule",
		editTitle: "Edit rule",
		ruleName: "Rule name",
		ruleNamePlaceholder: "Name this rule",
		delimiter: "Delimiter",
		delimiterDesc: "The marker that wraps the text, e.g. ++",
		css: "Style declarations",
		cssDesc:
			"Write only what goes inside the CSS curly braces { }, e.g. color: red;. Leave empty and the class below decides the styling from your own CSS snippet.",
		cssPlaceholder: `border: 1px solid var(--interactive-accent);
border-radius: 6px;
padding: 1px 5px;`,
		cssAria: "CSS style declarations",
		visualEdit: "Visual editor",
		visualEditHint:
			"Coming soon: tweak styles in a GUI instead of writing CSS by hand",
		className: "Class name (optional)",
		classNameDesc:
			"CSS class names added to the matched text, separated by spaces. With the declarations left empty, styling comes entirely from the rule you write for this class in a CSS snippet.",
		classNamePlaceholder: "my-highlight",
		exportName: "Export as CSS snippet",
		exportDesc:
			"Export rule declarations as a CSS snippet. Paste it into a CSS snippet file and enable it, then clear the rule's declarations so the snippet takes over — that way styles can be reused and overridden by themes.",
		exportBtn: "Export",
		exportTitle: "Export CSS snippet",
		exportEmpty: "No rule has declarations yet, so there is nothing to export.",
		copy: "Copy to clipboard",
		copied: "Copied",
		copyFailed: "Copy failed — select and copy manually",
		cancel: "Cancel",
		create: "Create",
		save: "Save",
		delimiterRequired: "Delimiter is required",
		conflictBuiltin: "Conflicts with built-in Markdown syntax \"{name}\"",
		conflictCustomCreate:
			"Conflicts with custom syntax \"{name}\" — confirm again to create (disabled)",
		conflictCustomSave:
			"Conflicts with custom syntax \"{name}\" — confirm again to save (disabled)",
		conflictAnnotation: "Conflicts with \"{name}\"",
		untitled: "Untitled",
	},
};

export function resolveLanguage(lang: Language): ResolvedLanguage {
	if (lang === "system") {
		const nav =
			typeof navigator !== "undefined" ? navigator.language || "" : "";
		return nav.toLowerCase().startsWith("zh") ? "zh" : "en";
	}
	return lang;
}

function getStrings(lang: ResolvedLanguage): UIStrings {
	return STRINGS[lang] ?? STRINGS.zh;
}

export function stringsFor(lang: Language): UIStrings {
	return getStrings(resolveLanguage(lang));
}

class ConfirmModal extends Modal {
	private message: string;
	private confirmLabel: string;
	private cancelLabel: string;
	private onConfirm: () => void;

	constructor(
		app: App,
		message: string,
		confirmLabel: string,
		cancelLabel: string,
		onConfirm: () => void
	) {
		super(app);
		this.message = message;
		this.confirmLabel = confirmLabel;
		this.cancelLabel = cancelLabel;
		this.onConfirm = onConfirm;
	}

	onOpen(): void {
		const { contentEl } = this;
		contentEl.createEl("p", {
			cls: "custom-syntax-confirm-message",
			text: this.message,
		});

		const btnRow = contentEl.createDiv({ cls: "custom-syntax-modal-actions" });
		const cancelBtn = btnRow.createEl("button", { text: this.cancelLabel });
		cancelBtn.addEventListener("click", () => this.close());

		const confirmBtn = btnRow.createEl("button", {
			text: this.confirmLabel,
			cls: "mod-warning",
		});
		confirmBtn.addEventListener("click", () => {
			this.close();
			this.onConfirm();
		});
	}
}

class RuleModal extends Modal {
	plugin: CustomSyntaxPlugin;
	rule: SyntaxRule | null;
	onDone: () => void;

	private nameInput!: HTMLInputElement;
	private delimInput!: HTMLInputElement;
	private classInput!: HTMLInputElement;
	private cssEditor!: CssEditorHandle;
	private errorEl!: HTMLElement;
	private pendingCustomConflict: SyntaxRule | null = null;

	constructor(
		app: App,
		plugin: CustomSyntaxPlugin,
		rule: SyntaxRule | null,
		onDone: () => void
	) {
		super(app);
		this.plugin = plugin;
		this.rule = rule;
		this.onDone = onDone;
	}

	onOpen(): void {
		const t = stringsFor(this.plugin.settings.language);
		this.titleEl.setText(this.rule ? t.editTitle : t.createTitle);
		const { contentEl } = this;

		new Setting(contentEl).setName(t.ruleName).addText((text) => {
			this.nameInput = text.inputEl;
			text
				.setValue(this.rule?.name ?? "")
				.setPlaceholder(t.ruleNamePlaceholder);
		});

		new Setting(contentEl)
			.setName(t.delimiter)
			.setDesc(t.delimiterDesc)
			.addText((text) => {
				this.delimInput = text.inputEl;
				text.setValue(this.rule?.delimiter ?? "++").setPlaceholder("++");
				this.delimInput.addEventListener("input", () => {
					this.pendingCustomConflict = null;
					this.clearError();
				});
			});

		new Setting(contentEl)
			.setName(t.className)
			.setDesc(t.classNameDesc)
			.addText((text) => {
				this.classInput = text.inputEl;
				text
					.setValue(this.rule?.className ?? "")
					.setPlaceholder(t.classNamePlaceholder);
			});

		// The declarations editor gets its own row, full width, under its
		// label — a side-by-side layout leaves far too little room for it.
		const cssSetting = new Setting(contentEl)
			.setName(t.css)
			.setDesc(t.cssDesc);
		cssSetting.settingEl.addClass("custom-syntax-stacked");
		// Editor + visual-edit button share one row; button sits on the right.
		const cssRow = cssSetting.controlEl.createDiv({
			cls: "custom-syntax-css-row",
		});
		const cssHost = cssRow.createDiv({
			cls: "custom-syntax-css-editor",
		});
		const visualBtn = cssRow.createEl("button", {
			text: t.visualEdit,
			cls: "custom-syntax-visual-edit",
		});
		visualBtn.disabled = true;
		visualBtn.title = t.visualEditHint;
		this.cssEditor = createCssEditor(
			cssHost,
			this.rule?.css ?? DEFAULT_SETTINGS.rules[0].css,
			{
				placeholderText: t.cssPlaceholder,
				ariaLabel: t.cssAria,
				onSubmit: () => this.onSubmit(),
			}
		);

		this.errorEl = contentEl.createDiv({ cls: "custom-syntax-error" });

		const btnRow = contentEl.createDiv({ cls: "custom-syntax-modal-actions" });
		const cancelBtn = btnRow.createEl("button", { text: t.cancel });
		cancelBtn.addEventListener("click", () => this.close());

		const submitBtn = btnRow.createEl("button", {
			text: this.rule ? t.save : t.create,
			cls: "mod-cta",
		});
		submitBtn.addEventListener("click", () => this.onSubmit());
	}

	private clearError(): void {
		this.errorEl.empty();
		this.errorEl.removeClass("is-visible");
	}

	private showError(msg: string): void {
		this.errorEl.empty();
		this.errorEl.createSpan({ text: msg });
		this.errorEl.addClass("is-visible");
	}

	private onSubmit(): void {
		const t = stringsFor(this.plugin.settings.language);
		const lang = resolveLanguage(this.plugin.settings.language);
		const name = this.nameInput.value.trim();
		const delimiter = this.delimInput.value;
		const css = this.cssEditor.getValue();
		const className = sanitizeClassName(this.classInput.value);

		if (!delimiter) {
			this.showError(t.delimiterRequired);
			return;
		}

		const builtin = findBuiltinConflict(delimiter);
		if (builtin) {
			const nm = lang === "zh" ? builtin.zh : builtin.en;
			this.showError(t.conflictBuiltin.replace("{name}", nm));
			this.pendingCustomConflict = null;
			return;
		}

		const custom = findCustomConflict(
			delimiter,
			this.plugin.settings.rules,
			this.rule?.id
		);
		if (custom) {
			const nm = custom.name || t.untitled;
			if (
				this.pendingCustomConflict &&
				this.pendingCustomConflict.id === custom.id
			) {
				this.finish(name, delimiter, css, className, false);
				return;
			}
			this.pendingCustomConflict = custom;
			const msg = this.rule ? t.conflictCustomSave : t.conflictCustomCreate;
			this.showError(msg.replace("{name}", nm));
			return;
		}

		this.finish(
			name,
			delimiter,
			css,
			className,
			this.rule ? this.rule.enabled : true
		);
	}

	private finish(
		name: string,
		delimiter: string,
		css: string,
		className: string,
		enabled: boolean
	): void {
		const t = stringsFor(this.plugin.settings.language);
		const finalName = name || t.untitled;

		if (this.rule) {
			this.rule.name = finalName;
			this.rule.delimiter = delimiter;
			this.rule.css = css;
			this.rule.className = className;
			this.rule.enabled = enabled;
			this.rule.conflictWithId = null;
		} else {
			this.plugin.settings.rules.push({
				id: newRuleId(),
				name: finalName,
				delimiter,
				css,
				className,
				enabled,
				conflictWithId: null,
			});
		}

		void this.plugin.saveSettings();
		this.close();
		this.onDone();
	}

	onClose(): void {
		this.cssEditor?.destroy();
		this.contentEl.empty();
	}
}

class ExportModal extends Modal {
	private content: string;
	private emptyMessage: string;
	private copyLabel: string;
	private copiedLabel: string;
	private failedLabel: string;

	constructor(
		app: App,
		content: string,
		emptyMessage: string,
		copyLabel: string,
		copiedLabel: string,
		failedLabel: string
	) {
		super(app);
		this.content = content;
		this.emptyMessage = emptyMessage;
		this.copyLabel = copyLabel;
		this.copiedLabel = copiedLabel;
		this.failedLabel = failedLabel;
	}

	onOpen(): void {
		const { contentEl } = this;

		if (!this.content) {
			contentEl.createEl("p", { text: this.emptyMessage });
			return;
		}

		const area = contentEl.createEl("textarea", {
			cls: "custom-syntax-export-area",
		});
		area.rows = 16;
		area.readOnly = true;
		area.spellcheck = false;
		area.value = this.content;
		area.setAttribute("aria-label", this.copyLabel);

		const actions = contentEl.createDiv({
			cls: "custom-syntax-modal-actions",
		});
		const copyBtn = actions.createEl("button", {
			text: this.copyLabel,
			cls: "mod-cta",
		});
		copyBtn.addEventListener("click", () => {
			area.select();
			void navigator.clipboard.writeText(this.content).then(
				() => copyBtn.setText(this.copiedLabel),
				() => copyBtn.setText(this.failedLabel)
			);
		});
	}
}

export class CustomSyntaxSettingTab extends PluginSettingTab {
	plugin: CustomSyntaxPlugin;

	constructor(app: App, plugin: CustomSyntaxPlugin) {
		super(app, plugin);
		this.plugin = plugin;
	}

	display(): void {
		const { containerEl } = this;
		containerEl.empty();
		const t = stringsFor(this.plugin.settings.language);

		const nav = containerEl.createDiv({ cls: "custom-syntax-nav" });
		const title = nav.createDiv({ cls: "custom-syntax-nav-title" });
		title.createSpan({ text: t.pluginName });
		title.createSpan({
			cls: "custom-syntax-nav-version",
			text: `v${this.plugin.manifest.version}`,
		});

		const actions = nav.createDiv({ cls: "custom-syntax-nav-actions" });

		const langSelect = actions.createEl("select");
		langSelect.addClass("dropdown");
		const options: Array<[Language, string]> = [
			["system", t.followSystem],
			["zh", "中文"],
			["en", "English"],
		];
		for (const [value, label] of options) {
			const opt = langSelect.createEl("option");
			opt.value = value;
			opt.textContent = label;
		}
		langSelect.value = this.plugin.settings.language;
		langSelect.addEventListener("change", () => {
			this.plugin.settings.language = langSelect.value as Language;
			void this.plugin.saveSettings();
			this.display();
		});

		const addBtn = actions.createEl("button", {
			text: t.addRule,
			cls: "mod-cta",
		});
		addBtn.addEventListener("click", () => {
			new RuleModal(this.app, this.plugin, null, () => this.display()).open();
		});

		const list = containerEl.createDiv({ cls: "custom-syntax-rules" });
		this.plugin.settings.rules.forEach((rule) => {
			this.renderRuleCard(list, rule);
		});

		new Setting(containerEl)
			.setName(t.exportName)
			.setDesc(t.exportDesc)
			.addButton((btn) =>
				btn.setButtonText(t.exportBtn).setCta().onClick(() => {
					new ExportModal(
						this.app,
						exportRulesAsCss(this.plugin.settings.rules),
						t.exportEmpty,
						t.copy,
						t.copied,
						t.copyFailed
					).open();
				})
			);
	}

	private renderRuleCard(containerEl: HTMLElement, rule: SyntaxRule): void {
		const t = stringsFor(this.plugin.settings.language);
		const card = containerEl.createDiv({ cls: "custom-syntax-rule-card" });

		const row = card.createDiv({ cls: "custom-syntax-rule-row" });

		const nameEl = row.createDiv({
			cls: "custom-syntax-rule-name",
			text: rule.name || t.untitled,
		});
		nameEl.title = rule.delimiter;

		const controls = row.createDiv({ cls: "custom-syntax-rule-controls" });

		const editBtn = controls.createEl("button", { cls: "clickable-icon" });
		editBtn.setAttribute("aria-label", t.edit);
		setIcon(editBtn, "pencil");
		editBtn.addEventListener("click", () => {
			new RuleModal(this.app, this.plugin, rule, () => this.display()).open();
		});

		const delBtn = controls.createEl("button", { cls: "clickable-icon" });
		delBtn.setAttribute("aria-label", t.delete);
		setIcon(delBtn, "trash");
		delBtn.addEventListener("click", () => {
			const name = rule.name || t.untitled;
			new ConfirmModal(
				this.app,
				t.deleteConfirm.replace("{name}", name),
				t.delete,
				t.cancel,
			() => {
				void this.deleteRule(rule);
			}
		).open();
		});

		// Native Obsidian toggle: the is-enabled class drives the look.
		const toggle = controls.createDiv({
			cls: rule.enabled ? "checkbox-container is-enabled" : "checkbox-container",
		});
		toggle.setAttribute("role", "switch");
		toggle.setAttribute("aria-checked", String(rule.enabled));
		toggle.setAttribute("aria-label", t.toggle);
		toggle.setAttribute("tabindex", "0");
		toggle.addEventListener("click", () => {
			const newVal = !rule.enabled;
			toggle.toggleClass("is-enabled", newVal);
			toggle.setAttribute("aria-checked", String(newVal));
			void this.toggleRule(rule, newVal);
			window.setTimeout(() => this.display(), 180);
		});
		toggle.addEventListener("keydown", (ev: KeyboardEvent) => {
			if (ev.key === " " || ev.key === "Enter") {
				ev.preventDefault();
				toggle.click();
			}
		});

		const extraClass = sanitizeClassName(rule.className);
		if (extraClass) {
			card.createDiv({
				cls: "custom-syntax-rule-class",
				text: `.${extraClass.split(" ").join(" .")}`,
			});
		}

		if (rule.conflictWithId) {
			const other = this.plugin.settings.rules.find(
				(r) => r.id === rule.conflictWithId
			);
			if (other) {
				card.createDiv({
					cls: "custom-syntax-rule-conflict",
					text: t.conflictAnnotation.replace(
						"{name}",
						other.name || t.untitled
					),
				});
			}
		}
	}

	private async toggleRule(rule: SyntaxRule, enabled: boolean): Promise<void> {
		rule.enabled = enabled;
		rule.conflictWithId = null;

		if (enabled) {
			for (const other of this.plugin.settings.rules) {
				if (
					other !== rule &&
					other.enabled &&
					delimitersConflict(rule.delimiter, other.delimiter)
				) {
					other.enabled = false;
					other.conflictWithId = rule.id;
				}
			}
		}

		await this.plugin.saveSettings();
	}

	private async deleteRule(rule: SyntaxRule): Promise<void> {
		this.plugin.settings.rules = this.plugin.settings.rules.filter(
			(r) => r !== rule
		);
		for (const r of this.plugin.settings.rules) {
			if (r.conflictWithId === rule.id) {
				r.conflictWithId = null;
			}
		}
		await this.plugin.saveSettings();
		this.display();
	}
}
